#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 71
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 15
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
    aux_sym_document_attr_token1 = 1,
    anon_sym_COLON = 2,
    aux_sym_element_attr_token1 = 3,
    anon_sym_RBRACK = 4,
    anon_sym_LBRACK = 5,
    anon_sym_SPACE = 6,
    anon_sym_x = 7,
    anon_sym_STAR = 8,
    aux_sym_line_token1 = 9,
    sym__NEWLINE = 10,
    sym__WHITE_SPACE = 11,
    sym__eof = 12,
    sym_title_h0_marker = 13,
    sym_title_h1_marker = 14,
    sym_title_h2_marker = 15,
    sym_title_h3_marker = 16,
    sym_title_h4_marker = 17,
    sym_title_h5_marker = 18,
    sym_list_marker_star = 19,
    sym_list_marker_hyphen = 20,
    sym_list_marker_dot = 21,
    sym_list_marker_digit = 22,
    sym_list_marker_geek = 23,
    sym_list_marker_alpha = 24,
    sym_document_attr_marker = 25,
    sym_element_attr_marker = 26,
    sym_document = 27,
    sym__section_block = 28,
    sym_title0 = 29,
    sym_title1 = 30,
    sym_title2 = 31,
    sym_title3 = 32,
    sym_title4 = 33,
    sym_title5 = 34,
    sym_document_attr = 35,
    sym_element_attr = 36,
    sym_checked_list = 37,
    sym_ck_item = 38,
    sym_unordered_list = 39,
    sym_ul_item = 40,
    sym_unordered_list_marker = 41,
    sym_ordered_list = 42,
    sym_ol_item = 43,
    sym_ordered_list_marker = 44,
    sym_line = 45,
    sym__block_end = 46,
    aux_sym_document_repeat1 = 47,
    aux_sym_title0_repeat1 = 48,
    aux_sym_checked_list_repeat1 = 49,
    aux_sym_unordered_list_repeat1 = 50,
    aux_sym_ordered_list_repeat1 = 51,
};

static const char *const ts_symbol_names[] = {
    [ts_builtin_sym_end] = "end",
    [aux_sym_document_attr_token1] = "document_attr_token1",
    [anon_sym_COLON] = ":",
    [aux_sym_element_attr_token1] = "element_attr_token1",
    [anon_sym_RBRACK] = "]",
    [anon_sym_LBRACK] = "[",
    [anon_sym_SPACE] = " ",
    [anon_sym_x] = "x",
    [anon_sym_STAR] = "*",
    [aux_sym_line_token1] = "line_token1",
    [sym__NEWLINE] = "_NEWLINE",
    [sym__WHITE_SPACE] = "_WHITE_SPACE",
    [sym__eof] = "_eof",
    [sym_title_h0_marker] = "title_h0_marker",
    [sym_title_h1_marker] = "title_h1_marker",
    [sym_title_h2_marker] = "title_h2_marker",
    [sym_title_h3_marker] = "title_h3_marker",
    [sym_title_h4_marker] = "title_h4_marker",
    [sym_title_h5_marker] = "title_h5_marker",
    [sym_list_marker_star] = "list_marker_star",
    [sym_list_marker_hyphen] = "list_marker_hyphen",
    [sym_list_marker_dot] = "list_marker_dot",
    [sym_list_marker_digit] = "list_marker_digit",
    [sym_list_marker_geek] = "list_marker_geek",
    [sym_list_marker_alpha] = "list_marker_alpha",
    [sym_document_attr_marker] = "document_attr_marker",
    [sym_element_attr_marker] = "element_attr_marker",
    [sym_document] = "document",
    [sym__section_block] = "_section_block",
    [sym_title0] = "title0",
    [sym_title1] = "title1",
    [sym_title2] = "title2",
    [sym_title3] = "title3",
    [sym_title4] = "title4",
    [sym_title5] = "title5",
    [sym_document_attr] = "document_attr",
    [sym_element_attr] = "element_attr",
    [sym_checked_list] = "checked_list",
    [sym_ck_item] = "ck_item",
    [sym_unordered_list] = "unordered_list",
    [sym_ul_item] = "ul_item",
    [sym_unordered_list_marker] = "unordered_list_marker",
    [sym_ordered_list] = "ordered_list",
    [sym_ol_item] = "ol_item",
    [sym_ordered_list_marker] = "ordered_list_marker",
    [sym_line] = "line",
    [sym__block_end] = "_block_end",
    [aux_sym_document_repeat1] = "document_repeat1",
    [aux_sym_title0_repeat1] = "title0_repeat1",
    [aux_sym_checked_list_repeat1] = "checked_list_repeat1",
    [aux_sym_unordered_list_repeat1] = "unordered_list_repeat1",
    [aux_sym_ordered_list_repeat1] = "ordered_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
    [ts_builtin_sym_end] = ts_builtin_sym_end,
    [aux_sym_document_attr_token1] = aux_sym_document_attr_token1,
    [anon_sym_COLON] = anon_sym_COLON,
    [aux_sym_element_attr_token1] = aux_sym_element_attr_token1,
    [anon_sym_RBRACK] = anon_sym_RBRACK,
    [anon_sym_LBRACK] = anon_sym_LBRACK,
    [anon_sym_SPACE] = anon_sym_SPACE,
    [anon_sym_x] = anon_sym_x,
    [anon_sym_STAR] = anon_sym_STAR,
    [aux_sym_line_token1] = aux_sym_line_token1,
    [sym__NEWLINE] = sym__NEWLINE,
    [sym__WHITE_SPACE] = sym__WHITE_SPACE,
    [sym__eof] = sym__eof,
    [sym_title_h0_marker] = sym_title_h0_marker,
    [sym_title_h1_marker] = sym_title_h1_marker,
    [sym_title_h2_marker] = sym_title_h2_marker,
    [sym_title_h3_marker] = sym_title_h3_marker,
    [sym_title_h4_marker] = sym_title_h4_marker,
    [sym_title_h5_marker] = sym_title_h5_marker,
    [sym_list_marker_star] = sym_list_marker_star,
    [sym_list_marker_hyphen] = sym_list_marker_hyphen,
    [sym_list_marker_dot] = sym_list_marker_dot,
    [sym_list_marker_digit] = sym_list_marker_digit,
    [sym_list_marker_geek] = sym_list_marker_geek,
    [sym_list_marker_alpha] = sym_list_marker_alpha,
    [sym_document_attr_marker] = sym_document_attr_marker,
    [sym_element_attr_marker] = sym_element_attr_marker,
    [sym_document] = sym_document,
    [sym__section_block] = sym__section_block,
    [sym_title0] = sym_title0,
    [sym_title1] = sym_title1,
    [sym_title2] = sym_title2,
    [sym_title3] = sym_title3,
    [sym_title4] = sym_title4,
    [sym_title5] = sym_title5,
    [sym_document_attr] = sym_document_attr,
    [sym_element_attr] = sym_element_attr,
    [sym_checked_list] = sym_checked_list,
    [sym_ck_item] = sym_ck_item,
    [sym_unordered_list] = sym_unordered_list,
    [sym_ul_item] = sym_ul_item,
    [sym_unordered_list_marker] = sym_unordered_list_marker,
    [sym_ordered_list] = sym_ordered_list,
    [sym_ol_item] = sym_ol_item,
    [sym_ordered_list_marker] = sym_ordered_list_marker,
    [sym_line] = sym_line,
    [sym__block_end] = sym__block_end,
    [aux_sym_document_repeat1] = aux_sym_document_repeat1,
    [aux_sym_title0_repeat1] = aux_sym_title0_repeat1,
    [aux_sym_checked_list_repeat1] = aux_sym_checked_list_repeat1,
    [aux_sym_unordered_list_repeat1] = aux_sym_unordered_list_repeat1,
    [aux_sym_ordered_list_repeat1] = aux_sym_ordered_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
    [ts_builtin_sym_end] = {
        .visible = false,
        .named = true,
    },
    [aux_sym_document_attr_token1] = {
        .visible = false,
        .named = false,
    },
    [anon_sym_COLON] = {
        .visible = true,
        .named = false,
    },
    [aux_sym_element_attr_token1] = {
        .visible = false,
        .named = false,
    },
    [anon_sym_RBRACK] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_LBRACK] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_SPACE] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_x] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_STAR] = {
        .visible = true,
        .named = false,
    },
    [aux_sym_line_token1] = {
        .visible = false,
        .named = false,
    },
    [sym__NEWLINE] = {
        .visible = false,
        .named = true,
    },
    [sym__WHITE_SPACE] = {
        .visible = false,
        .named = true,
    },
    [sym__eof] = {
        .visible = false,
        .named = true,
    },
    [sym_title_h0_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h1_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h2_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h3_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h4_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h5_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_star] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_hyphen] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_dot] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_digit] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_geek] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_alpha] = {
        .visible = true,
        .named = true,
    },
    [sym_document_attr_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_element_attr_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_document] = {
        .visible = true,
        .named = true,
    },
    [sym__section_block] = {
        .visible = false,
        .named = true,
    },
    [sym_title0] = {
        .visible = true,
        .named = true,
    },
    [sym_title1] = {
        .visible = true,
        .named = true,
    },
    [sym_title2] = {
        .visible = true,
        .named = true,
    },
    [sym_title3] = {
        .visible = true,
        .named = true,
    },
    [sym_title4] = {
        .visible = true,
        .named = true,
    },
    [sym_title5] = {
        .visible = true,
        .named = true,
    },
    [sym_document_attr] = {
        .visible = true,
        .named = true,
    },
    [sym_element_attr] = {
        .visible = true,
        .named = true,
    },
    [sym_checked_list] = {
        .visible = true,
        .named = true,
    },
    [sym_ck_item] = {
        .visible = true,
        .named = true,
    },
    [sym_unordered_list] = {
        .visible = true,
        .named = true,
    },
    [sym_ul_item] = {
        .visible = true,
        .named = true,
    },
    [sym_unordered_list_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_ordered_list] = {
        .visible = true,
        .named = true,
    },
    [sym_ol_item] = {
        .visible = true,
        .named = true,
    },
    [sym_ordered_list_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_line] = {
        .visible = true,
        .named = true,
    },
    [sym__block_end] = {
        .visible = false,
        .named = true,
    },
    [aux_sym_document_repeat1] = {
        .visible = false,
        .named = false,
    },
    [aux_sym_title0_repeat1] = {
        .visible = false,
        .named = false,
    },
    [aux_sym_checked_list_repeat1] = {
        .visible = false,
        .named = false,
    },
    [aux_sym_unordered_list_repeat1] = {
        .visible = false,
        .named = false,
    },
    [aux_sym_ordered_list_repeat1] = {
        .visible = false,
        .named = false,
    },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
    [0] = { 0 },
};

static const uint16_t ts_non_terminal_alias_map[] = {
    0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
    [0] = 0,
    [1] = 1,
    [2] = 2,
    [3] = 3,
    [4] = 4,
    [5] = 5,
    [6] = 6,
    [7] = 7,
    [8] = 8,
    [9] = 9,
    [10] = 10,
    [11] = 11,
    [12] = 12,
    [13] = 13,
    [14] = 14,
    [15] = 15,
    [16] = 16,
    [17] = 17,
    [18] = 18,
    [19] = 19,
    [20] = 20,
    [21] = 21,
    [22] = 22,
    [23] = 23,
    [24] = 11,
    [25] = 25,
    [26] = 26,
    [27] = 27,
    [28] = 28,
    [29] = 29,
    [30] = 11,
    [31] = 31,
    [32] = 32,
    [33] = 33,
    [34] = 34,
    [35] = 11,
    [36] = 36,
    [37] = 34,
    [38] = 38,
    [39] = 34,
    [40] = 34,
    [41] = 41,
    [42] = 42,
    [43] = 43,
    [44] = 44,
    [45] = 45,
    [46] = 46,
    [47] = 47,
    [48] = 48,
    [49] = 49,
    [50] = 50,
    [51] = 51,
    [52] = 52,
    [53] = 53,
    [54] = 54,
    [55] = 55,
    [56] = 56,
    [57] = 57,
    [58] = 58,
    [59] = 59,
    [60] = 60,
    [61] = 61,
    [62] = 62,
    [63] = 63,
    [64] = 64,
    [65] = 65,
    [66] = 66,
    [67] = 67,
    [68] = 68,
    [69] = 69,
    [70] = 70,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
    START_LEXER();
    eof = lexer->eof(lexer);
    switch(state) {
        case 0:
            if(eof)
                ADVANCE(6);
            ADVANCE_MAP(
                '\t', 22,
                '\n', 21,
                '\r', 1,
                ' ', 15,
                '*', 18,
                ':', 8,
                '[', 12,
                ']', 11,
                'x', 17,
            );
            if(('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(7);
            END_STATE();
        case 1:
            if(lookahead == '\n')
                ADVANCE(21);
            END_STATE();
        case 2:
            if(lookahead == '\n')
                ADVANCE(21);
            if(lookahead == '\r')
                ADVANCE(1);
            if(lookahead == ' ')
                ADVANCE(14);
            if(lookahead == '*')
                ADVANCE(18);
            if(lookahead == 'x')
                ADVANCE(16);
            END_STATE();
        case 3:
            if(lookahead == '\n')
                ADVANCE(21);
            if(lookahead == '\r')
                ADVANCE(1);
            if(lookahead == '\t' ||
               lookahead == ' ')
                ADVANCE(22);
            if(('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(7);
            END_STATE();
        case 4:
            if(lookahead == '\n')
                ADVANCE(21);
            if(lookahead == '\r')
                ADVANCE(19);
            if(lookahead == '[')
                ADVANCE(13);
            if(lookahead != 0)
                ADVANCE(20);
            END_STATE();
        case 5:
            if(lookahead == '\n')
                ADVANCE(21);
            if(lookahead == '\r')
                ADVANCE(19);
            if(lookahead != 0)
                ADVANCE(20);
            END_STATE();
        case 6:
            ACCEPT_TOKEN(ts_builtin_sym_end);
            END_STATE();
        case 7:
            ACCEPT_TOKEN(aux_sym_document_attr_token1);
            if(lookahead == '-' ||
               ('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(7);
            END_STATE();
        case 8:
            ACCEPT_TOKEN(anon_sym_COLON);
            END_STATE();
        case 9:
            ACCEPT_TOKEN(aux_sym_element_attr_token1);
            if(lookahead == '\n')
                ADVANCE(21);
            if(lookahead == '\r')
                ADVANCE(1);
            if(lookahead != 0 &&
               lookahead != ']')
                ADVANCE(10);
            END_STATE();
        case 10:
            ACCEPT_TOKEN(aux_sym_element_attr_token1);
            if(lookahead != 0 &&
               lookahead != '\n' &&
               lookahead != '\r' &&
               lookahead != ']')
                ADVANCE(10);
            END_STATE();
        case 11:
            ACCEPT_TOKEN(anon_sym_RBRACK);
            END_STATE();
        case 12:
            ACCEPT_TOKEN(anon_sym_LBRACK);
            END_STATE();
        case 13:
            ACCEPT_TOKEN(anon_sym_LBRACK);
            if(lookahead != 0 &&
               lookahead != '\n')
                ADVANCE(20);
            END_STATE();
        case 14:
            ACCEPT_TOKEN(anon_sym_SPACE);
            END_STATE();
        case 15:
            ACCEPT_TOKEN(anon_sym_SPACE);
            if(lookahead == '\t' ||
               lookahead == ' ')
                ADVANCE(22);
            END_STATE();
        case 16:
            ACCEPT_TOKEN(anon_sym_x);
            END_STATE();
        case 17:
            ACCEPT_TOKEN(anon_sym_x);
            if(lookahead == '-' ||
               ('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(7);
            END_STATE();
        case 18:
            ACCEPT_TOKEN(anon_sym_STAR);
            END_STATE();
        case 19:
            ACCEPT_TOKEN(aux_sym_line_token1);
            if(lookahead == '\n')
                ADVANCE(21);
            if(lookahead != 0)
                ADVANCE(20);
            END_STATE();
        case 20:
            ACCEPT_TOKEN(aux_sym_line_token1);
            if(lookahead != 0 &&
               lookahead != '\n')
                ADVANCE(20);
            END_STATE();
        case 21:
            ACCEPT_TOKEN(sym__NEWLINE);
            END_STATE();
        case 22:
            ACCEPT_TOKEN(sym__WHITE_SPACE);
            if(lookahead == '\t' ||
               lookahead == ' ')
                ADVANCE(22);
            END_STATE();
        default:
            return false;
    }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
    [0] = { .lex_state = 0, .external_lex_state = 1 },
    [1] = { .lex_state = 0, .external_lex_state = 2 },
    [2] = { .lex_state = 0, .external_lex_state = 2 },
    [3] = { .lex_state = 0, .external_lex_state = 2 },
    [4] = { .lex_state = 0, .external_lex_state = 3 },
    [5] = { .lex_state = 0, .external_lex_state = 2 },
    [6] = { .lex_state = 0, .external_lex_state = 2 },
    [7] = { .lex_state = 0, .external_lex_state = 2 },
    [8] = { .lex_state = 0, .external_lex_state = 2 },
    [9] = { .lex_state = 0, .external_lex_state = 2 },
    [10] = { .lex_state = 0, .external_lex_state = 2 },
    [11] = { .lex_state = 0, .external_lex_state = 2 },
    [12] = { .lex_state = 0, .external_lex_state = 2 },
    [13] = { .lex_state = 0, .external_lex_state = 2 },
    [14] = { .lex_state = 0, .external_lex_state = 2 },
    [15] = { .lex_state = 0, .external_lex_state = 2 },
    [16] = { .lex_state = 0, .external_lex_state = 2 },
    [17] = { .lex_state = 0, .external_lex_state = 4 },
    [18] = { .lex_state = 0, .external_lex_state = 4 },
    [19] = { .lex_state = 0, .external_lex_state = 5 },
    [20] = { .lex_state = 0, .external_lex_state = 5 },
    [21] = { .lex_state = 0, .external_lex_state = 5 },
    [22] = { .lex_state = 0, .external_lex_state = 3 },
    [23] = { .lex_state = 0, .external_lex_state = 5 },
    [24] = { .lex_state = 0, .external_lex_state = 4 },
    [25] = { .lex_state = 0, .external_lex_state = 4 },
    [26] = { .lex_state = 0, .external_lex_state = 6 },
    [27] = { .lex_state = 0, .external_lex_state = 6 },
    [28] = { .lex_state = 0, .external_lex_state = 6 },
    [29] = { .lex_state = 4 },
    [30] = { .lex_state = 0, .external_lex_state = 5 },
    [31] = { .lex_state = 0, .external_lex_state = 5 },
    [32] = { .lex_state = 2 },
    [33] = { .lex_state = 0, .external_lex_state = 5 },
    [34] = { .lex_state = 0, .external_lex_state = 7 },
    [35] = { .lex_state = 0, .external_lex_state = 6 },
    [36] = { .lex_state = 5 },
    [37] = { .lex_state = 0, .external_lex_state = 7 },
    [38] = { .lex_state = 5 },
    [39] = { .lex_state = 0, .external_lex_state = 7 },
    [40] = { .lex_state = 0, .external_lex_state = 7 },
    [41] = { .lex_state = 5 },
    [42] = { .lex_state = 0, .external_lex_state = 6 },
    [43] = { .lex_state = 5 },
    [44] = { .lex_state = 5 },
    [45] = { .lex_state = 5 },
    [46] = { .lex_state = 5 },
    [47] = { .lex_state = 5 },
    [48] = { .lex_state = 5 },
    [49] = { .lex_state = 5 },
    [50] = { .lex_state = 3 },
    [51] = { .lex_state = 0 },
    [52] = { .lex_state = 3 },
    [53] = { .lex_state = 3 },
    [54] = { .lex_state = 0 },
    [55] = { .lex_state = 0 },
    [56] = { .lex_state = 0 },
    [57] = { .lex_state = 3 },
    [58] = { .lex_state = 3 },
    [59] = { .lex_state = 3 },
    [60] = { .lex_state = 3 },
    [61] = { .lex_state = 3 },
    [62] = { .lex_state = 3 },
    [63] = { .lex_state = 9 },
    [64] = { .lex_state = 0 },
    [65] = { .lex_state = 3 },
    [66] = { .lex_state = 3 },
    [67] = { .lex_state = 3 },
    [68] = { .lex_state = 3 },
    [69] = { .lex_state = 3 },
    [70] = { .lex_state = 0 },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
    [0] = {
        [ts_builtin_sym_end] = ACTIONS(1),
        [aux_sym_document_attr_token1] = ACTIONS(1),
        [anon_sym_COLON] = ACTIONS(1),
        [anon_sym_RBRACK] = ACTIONS(1),
        [anon_sym_LBRACK] = ACTIONS(1),
        [anon_sym_SPACE] = ACTIONS(1),
        [anon_sym_x] = ACTIONS(1),
        [anon_sym_STAR] = ACTIONS(1),
        [sym__NEWLINE] = ACTIONS(3),
        [sym__WHITE_SPACE] = ACTIONS(1),
        [sym__eof] = ACTIONS(1),
        [sym_title_h0_marker] = ACTIONS(1),
        [sym_title_h1_marker] = ACTIONS(1),
        [sym_title_h2_marker] = ACTIONS(1),
        [sym_title_h3_marker] = ACTIONS(1),
        [sym_title_h4_marker] = ACTIONS(1),
        [sym_title_h5_marker] = ACTIONS(1),
        [sym_list_marker_star] = ACTIONS(1),
        [sym_list_marker_hyphen] = ACTIONS(1),
        [sym_list_marker_dot] = ACTIONS(1),
        [sym_list_marker_digit] = ACTIONS(1),
        [sym_list_marker_geek] = ACTIONS(1),
        [sym_list_marker_alpha] = ACTIONS(1),
        [sym_document_attr_marker] = ACTIONS(1),
        [sym_element_attr_marker] = ACTIONS(1),
    },
    [1] = {
        [sym_document] = STATE(64),
        [sym__section_block] = STATE(3),
        [sym_title0] = STATE(3),
        [sym_title1] = STATE(3),
        [sym_title2] = STATE(3),
        [sym_title3] = STATE(3),
        [sym_title4] = STATE(3),
        [sym_title5] = STATE(3),
        [sym_element_attr] = STATE(4),
        [sym_checked_list] = STATE(3),
        [sym_ck_item] = STATE(19),
        [sym_unordered_list] = STATE(3),
        [sym_ul_item] = STATE(20),
        [sym_unordered_list_marker] = STATE(66),
        [sym_ordered_list] = STATE(3),
        [sym_ol_item] = STATE(17),
        [sym_ordered_list_marker] = STATE(67),
        [aux_sym_document_repeat1] = STATE(3),
        [aux_sym_checked_list_repeat1] = STATE(19),
        [aux_sym_unordered_list_repeat1] = STATE(20),
        [aux_sym_ordered_list_repeat1] = STATE(17),
        [ts_builtin_sym_end] = ACTIONS(5),
        [sym__NEWLINE] = ACTIONS(3),
        [sym_title_h0_marker] = ACTIONS(7),
        [sym_title_h1_marker] = ACTIONS(9),
        [sym_title_h2_marker] = ACTIONS(11),
        [sym_title_h3_marker] = ACTIONS(13),
        [sym_title_h4_marker] = ACTIONS(15),
        [sym_title_h5_marker] = ACTIONS(17),
        [sym_list_marker_star] = ACTIONS(19),
        [sym_list_marker_hyphen] = ACTIONS(19),
        [sym_list_marker_dot] = ACTIONS(21),
        [sym_list_marker_digit] = ACTIONS(21),
        [sym_list_marker_geek] = ACTIONS(21),
        [sym_list_marker_alpha] = ACTIONS(21),
        [sym_element_attr_marker] = ACTIONS(23),
    },
    [2] = {
        [sym__section_block] = STATE(2),
        [sym_title0] = STATE(2),
        [sym_title1] = STATE(2),
        [sym_title2] = STATE(2),
        [sym_title3] = STATE(2),
        [sym_title4] = STATE(2),
        [sym_title5] = STATE(2),
        [sym_element_attr] = STATE(4),
        [sym_checked_list] = STATE(2),
        [sym_ck_item] = STATE(19),
        [sym_unordered_list] = STATE(2),
        [sym_ul_item] = STATE(20),
        [sym_unordered_list_marker] = STATE(66),
        [sym_ordered_list] = STATE(2),
        [sym_ol_item] = STATE(17),
        [sym_ordered_list_marker] = STATE(67),
        [aux_sym_document_repeat1] = STATE(2),
        [aux_sym_checked_list_repeat1] = STATE(19),
        [aux_sym_unordered_list_repeat1] = STATE(20),
        [aux_sym_ordered_list_repeat1] = STATE(17),
        [ts_builtin_sym_end] = ACTIONS(25),
        [sym__NEWLINE] = ACTIONS(3),
        [sym_title_h0_marker] = ACTIONS(27),
        [sym_title_h1_marker] = ACTIONS(30),
        [sym_title_h2_marker] = ACTIONS(33),
        [sym_title_h3_marker] = ACTIONS(36),
        [sym_title_h4_marker] = ACTIONS(39),
        [sym_title_h5_marker] = ACTIONS(42),
        [sym_list_marker_star] = ACTIONS(45),
        [sym_list_marker_hyphen] = ACTIONS(45),
        [sym_list_marker_dot] = ACTIONS(48),
        [sym_list_marker_digit] = ACTIONS(48),
        [sym_list_marker_geek] = ACTIONS(48),
        [sym_list_marker_alpha] = ACTIONS(48),
        [sym_element_attr_marker] = ACTIONS(51),
    },
    [3] = {
        [sym__section_block] = STATE(2),
        [sym_title0] = STATE(2),
        [sym_title1] = STATE(2),
        [sym_title2] = STATE(2),
        [sym_title3] = STATE(2),
        [sym_title4] = STATE(2),
        [sym_title5] = STATE(2),
        [sym_element_attr] = STATE(4),
        [sym_checked_list] = STATE(2),
        [sym_ck_item] = STATE(19),
        [sym_unordered_list] = STATE(2),
        [sym_ul_item] = STATE(20),
        [sym_unordered_list_marker] = STATE(66),
        [sym_ordered_list] = STATE(2),
        [sym_ol_item] = STATE(17),
        [sym_ordered_list_marker] = STATE(67),
        [aux_sym_document_repeat1] = STATE(2),
        [aux_sym_checked_list_repeat1] = STATE(19),
        [aux_sym_unordered_list_repeat1] = STATE(20),
        [aux_sym_ordered_list_repeat1] = STATE(17),
        [ts_builtin_sym_end] = ACTIONS(54),
        [sym__NEWLINE] = ACTIONS(3),
        [sym_title_h0_marker] = ACTIONS(7),
        [sym_title_h1_marker] = ACTIONS(9),
        [sym_title_h2_marker] = ACTIONS(11),
        [sym_title_h3_marker] = ACTIONS(13),
        [sym_title_h4_marker] = ACTIONS(15),
        [sym_title_h5_marker] = ACTIONS(17),
        [sym_list_marker_star] = ACTIONS(19),
        [sym_list_marker_hyphen] = ACTIONS(19),
        [sym_list_marker_dot] = ACTIONS(21),
        [sym_list_marker_digit] = ACTIONS(21),
        [sym_list_marker_geek] = ACTIONS(21),
        [sym_list_marker_alpha] = ACTIONS(21),
        [sym_element_attr_marker] = ACTIONS(23),
    },
};

static const uint16_t ts_small_parse_table[] = {
    [0] = 9,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    STATE(66),
    1,
    sym_unordered_list_marker,
    STATE(67),
    1,
    sym_ordered_list_marker,
    ACTIONS(19),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    STATE(17),
    2,
    sym_ol_item,
    aux_sym_ordered_list_repeat1,
    STATE(19),
    2,
    sym_ck_item,
    aux_sym_checked_list_repeat1,
    STATE(20),
    2,
    sym_ul_item,
    aux_sym_unordered_list_repeat1,
    STATE(16),
    3,
    sym_checked_list,
    sym_unordered_list,
    sym_ordered_list,
    ACTIONS(21),
    4,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    [37] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(56),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [57] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(58),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [77] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(60),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [97] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(62),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [117] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(64),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [137] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(66),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [157] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(68),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [177] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(70),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [197] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(72),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [217] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(74),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [237] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(76),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [257] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(78),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [277] = 5,
    STATE(10),
    1,
    sym__block_end,
    STATE(67),
    1,
    sym_ordered_list_marker,
    ACTIONS(80),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(18),
    2,
    sym_ol_item,
    aux_sym_ordered_list_repeat1,
    ACTIONS(21),
    4,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    [298] = 4,
    STATE(67),
    1,
    sym_ordered_list_marker,
    ACTIONS(82),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(18),
    2,
    sym_ol_item,
    aux_sym_ordered_list_repeat1,
    ACTIONS(84),
    4,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    [316] = 5,
    STATE(15),
    1,
    sym__block_end,
    STATE(69),
    1,
    sym_unordered_list_marker,
    ACTIONS(19),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    ACTIONS(87),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(23),
    2,
    sym_ck_item,
    aux_sym_checked_list_repeat1,
    [335] = 5,
    STATE(13),
    1,
    sym__block_end,
    STATE(68),
    1,
    sym_unordered_list_marker,
    ACTIONS(19),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    ACTIONS(89),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(21),
    2,
    sym_ul_item,
    aux_sym_unordered_list_repeat1,
    [354] = 4,
    STATE(68),
    1,
    sym_unordered_list_marker,
    ACTIONS(91),
    2,
    sym__eof,
    sym__NEWLINE,
    ACTIONS(93),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    STATE(21),
    2,
    sym_ul_item,
    aux_sym_unordered_list_repeat1,
    [370] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(96),
    6,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    [382] = 4,
    STATE(69),
    1,
    sym_unordered_list_marker,
    ACTIONS(98),
    2,
    sym__eof,
    sym__NEWLINE,
    ACTIONS(100),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    STATE(23),
    2,
    sym_ck_item,
    aux_sym_checked_list_repeat1,
    [398] = 1,
    ACTIONS(68),
    6,
    sym__eof,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym__NEWLINE,
    [407] = 1,
    ACTIONS(103),
    6,
    sym__eof,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym__NEWLINE,
    [416] = 4,
    ACTIONS(107),
    1,
    sym_document_attr_marker,
    STATE(14),
    1,
    sym__block_end,
    ACTIONS(105),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(28),
    2,
    sym_document_attr,
    aux_sym_title0_repeat1,
    [431] = 4,
    ACTIONS(107),
    1,
    sym_document_attr_marker,
    STATE(12),
    1,
    sym__block_end,
    ACTIONS(109),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(26),
    2,
    sym_document_attr,
    aux_sym_title0_repeat1,
    [446] = 3,
    ACTIONS(113),
    1,
    sym_document_attr_marker,
    ACTIONS(111),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(28),
    2,
    sym_document_attr,
    aux_sym_title0_repeat1,
    [458] = 4,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(116),
    1,
    anon_sym_LBRACK,
    ACTIONS(118),
    1,
    aux_sym_line_token1,
    STATE(33),
    1,
    sym_line,
    [471] = 1,
    ACTIONS(68),
    4,
    sym__eof,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym__NEWLINE,
    [478] = 1,
    ACTIONS(120),
    4,
    sym__eof,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym__NEWLINE,
    [485] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(122),
    3,
    anon_sym_SPACE,
    anon_sym_x,
    anon_sym_STAR,
    [494] = 1,
    ACTIONS(124),
    4,
    sym__eof,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym__NEWLINE,
    [501] = 2,
    STATE(24),
    1,
    sym__block_end,
    ACTIONS(126),
    2,
    sym__eof,
    sym__NEWLINE,
    [509] = 1,
    ACTIONS(68),
    3,
    sym__eof,
    sym_document_attr_marker,
    sym__NEWLINE,
    [515] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    aux_sym_line_token1,
    STATE(25),
    1,
    sym_line,
    [525] = 2,
    STATE(30),
    1,
    sym__block_end,
    ACTIONS(130),
    2,
    sym__eof,
    sym__NEWLINE,
    [533] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(132),
    1,
    aux_sym_line_token1,
    STATE(27),
    1,
    sym_line,
    [543] = 2,
    STATE(11),
    1,
    sym__block_end,
    ACTIONS(134),
    2,
    sym__eof,
    sym__NEWLINE,
    [551] = 2,
    STATE(35),
    1,
    sym__block_end,
    ACTIONS(136),
    2,
    sym__eof,
    sym__NEWLINE,
    [559] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(138),
    1,
    aux_sym_line_token1,
    STATE(9),
    1,
    sym_line,
    [569] = 1,
    ACTIONS(140),
    3,
    sym__eof,
    sym_document_attr_marker,
    sym__NEWLINE,
    [575] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(118),
    1,
    aux_sym_line_token1,
    STATE(31),
    1,
    sym_line,
    [585] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(132),
    1,
    aux_sym_line_token1,
    STATE(42),
    1,
    sym_line,
    [595] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(138),
    1,
    aux_sym_line_token1,
    STATE(5),
    1,
    sym_line,
    [605] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(138),
    1,
    aux_sym_line_token1,
    STATE(6),
    1,
    sym_line,
    [615] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(138),
    1,
    aux_sym_line_token1,
    STATE(7),
    1,
    sym_line,
    [625] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(138),
    1,
    aux_sym_line_token1,
    STATE(8),
    1,
    sym_line,
    [635] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(118),
    1,
    aux_sym_line_token1,
    STATE(33),
    1,
    sym_line,
    [645] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(142),
    1,
    sym__WHITE_SPACE,
    [652] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(144),
    1,
    anon_sym_LBRACK,
    [659] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(146),
    1,
    aux_sym_document_attr_token1,
    [666] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(148),
    1,
    sym__WHITE_SPACE,
    [673] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(150),
    1,
    anon_sym_RBRACK,
    [680] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(152),
    1,
    anon_sym_RBRACK,
    [687] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(154),
    1,
    anon_sym_COLON,
    [694] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(156),
    1,
    sym__WHITE_SPACE,
    [701] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(158),
    1,
    sym__WHITE_SPACE,
    [708] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(160),
    1,
    sym__WHITE_SPACE,
    [715] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(162),
    1,
    sym__WHITE_SPACE,
    [722] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(164),
    1,
    sym__WHITE_SPACE,
    [729] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(166),
    1,
    sym__WHITE_SPACE,
    [736] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(168),
    1,
    aux_sym_element_attr_token1,
    [743] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(170),
    1,
    ts_builtin_sym_end,
    [750] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(172),
    1,
    sym__WHITE_SPACE,
    [757] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(174),
    1,
    sym__WHITE_SPACE,
    [764] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(176),
    1,
    sym__WHITE_SPACE,
    [771] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(178),
    1,
    sym__WHITE_SPACE,
    [778] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(180),
    1,
    sym__WHITE_SPACE,
    [785] = 1,
    ACTIONS(182),
    1,
    sym__NEWLINE,
};

static const uint32_t ts_small_parse_table_map[] = {
    [SMALL_STATE(4)] = 0,
    [SMALL_STATE(5)] = 37,
    [SMALL_STATE(6)] = 57,
    [SMALL_STATE(7)] = 77,
    [SMALL_STATE(8)] = 97,
    [SMALL_STATE(9)] = 117,
    [SMALL_STATE(10)] = 137,
    [SMALL_STATE(11)] = 157,
    [SMALL_STATE(12)] = 177,
    [SMALL_STATE(13)] = 197,
    [SMALL_STATE(14)] = 217,
    [SMALL_STATE(15)] = 237,
    [SMALL_STATE(16)] = 257,
    [SMALL_STATE(17)] = 277,
    [SMALL_STATE(18)] = 298,
    [SMALL_STATE(19)] = 316,
    [SMALL_STATE(20)] = 335,
    [SMALL_STATE(21)] = 354,
    [SMALL_STATE(22)] = 370,
    [SMALL_STATE(23)] = 382,
    [SMALL_STATE(24)] = 398,
    [SMALL_STATE(25)] = 407,
    [SMALL_STATE(26)] = 416,
    [SMALL_STATE(27)] = 431,
    [SMALL_STATE(28)] = 446,
    [SMALL_STATE(29)] = 458,
    [SMALL_STATE(30)] = 471,
    [SMALL_STATE(31)] = 478,
    [SMALL_STATE(32)] = 485,
    [SMALL_STATE(33)] = 494,
    [SMALL_STATE(34)] = 501,
    [SMALL_STATE(35)] = 509,
    [SMALL_STATE(36)] = 515,
    [SMALL_STATE(37)] = 525,
    [SMALL_STATE(38)] = 533,
    [SMALL_STATE(39)] = 543,
    [SMALL_STATE(40)] = 551,
    [SMALL_STATE(41)] = 559,
    [SMALL_STATE(42)] = 569,
    [SMALL_STATE(43)] = 575,
    [SMALL_STATE(44)] = 585,
    [SMALL_STATE(45)] = 595,
    [SMALL_STATE(46)] = 605,
    [SMALL_STATE(47)] = 615,
    [SMALL_STATE(48)] = 625,
    [SMALL_STATE(49)] = 635,
    [SMALL_STATE(50)] = 645,
    [SMALL_STATE(51)] = 652,
    [SMALL_STATE(52)] = 659,
    [SMALL_STATE(53)] = 666,
    [SMALL_STATE(54)] = 673,
    [SMALL_STATE(55)] = 680,
    [SMALL_STATE(56)] = 687,
    [SMALL_STATE(57)] = 694,
    [SMALL_STATE(58)] = 701,
    [SMALL_STATE(59)] = 708,
    [SMALL_STATE(60)] = 715,
    [SMALL_STATE(61)] = 722,
    [SMALL_STATE(62)] = 729,
    [SMALL_STATE(63)] = 736,
    [SMALL_STATE(64)] = 743,
    [SMALL_STATE(65)] = 750,
    [SMALL_STATE(66)] = 757,
    [SMALL_STATE(67)] = 764,
    [SMALL_STATE(68)] = 771,
    [SMALL_STATE(69)] = 778,
    [SMALL_STATE(70)] = 785,
};

static const TSParseActionEntry ts_parse_actions[] = {
    [0] = { .entry = { .count = 0, .reusable = false } },
    [1] = { .entry = { .count = 1, .reusable = false } },
    RECOVER(),
    [3] = { .entry = { .count = 1, .reusable = true } },
    SHIFT_EXTRA(),
    [5] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_document, 0, 0, 0),
    [7] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(50),
    [9] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(65),
    [11] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(57),
    [13] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(53),
    [15] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(58),
    [17] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(60),
    [19] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(61),
    [21] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(62),
    [23] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(63),
    [25] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    [27] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(50),
    [30] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(65),
    [33] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(57),
    [36] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(53),
    [39] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(58),
    [42] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(60),
    [45] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(61),
    [48] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(62),
    [51] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(63),
    [54] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_document, 1, 0, 0),
    [56] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title5, 3, 0, 0),
    [58] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title4, 3, 0, 0),
    [60] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title3, 3, 0, 0),
    [62] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title2, 3, 0, 0),
    [64] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title1, 3, 0, 0),
    [66] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ordered_list, 2, 0, 0),
    [68] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_line, 2, 0, 0),
    [70] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title0, 4, 0, 0),
    [72] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_unordered_list, 2, 0, 0),
    [74] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title0, 5, 0, 0),
    [76] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_checked_list, 2, 0, 0),
    [78] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym__section_block, 2, 0, 0),
    [80] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(10),
    [82] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_ordered_list_repeat1, 2, 0, 0),
    [84] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_ordered_list_repeat1, 2, 0, 0),
    SHIFT_REPEAT(62),
    [87] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(15),
    [89] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(13),
    [91] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_unordered_list_repeat1, 2, 0, 0),
    [93] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_unordered_list_repeat1, 2, 0, 0),
    SHIFT_REPEAT(61),
    [96] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_element_attr, 4, 0, 0),
    [98] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_checked_list_repeat1, 2, 0, 0),
    [100] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_checked_list_repeat1, 2, 0, 0),
    SHIFT_REPEAT(61),
    [103] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ol_item, 3, 0, 0),
    [105] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(14),
    [107] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(52),
    [109] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(12),
    [111] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_title0_repeat1, 2, 0, 0),
    [113] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_title0_repeat1, 2, 0, 0),
    SHIFT_REPEAT(52),
    [116] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(32),
    [118] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(37),
    [120] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ck_item, 7, 0, 0),
    [122] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(55),
    [124] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ul_item, 3, 0, 0),
    [126] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(24),
    [128] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(34),
    [130] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(30),
    [132] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(40),
    [134] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(11),
    [136] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(35),
    [138] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(39),
    [140] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_document_attr, 4, 0, 0),
    [142] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(38),
    [144] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(32),
    [146] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(56),
    [148] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(47),
    [150] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(70),
    [152] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(59),
    [154] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(44),
    [156] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(48),
    [158] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(46),
    [160] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(43),
    [162] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(45),
    [164] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_unordered_list_marker, 1, 0, 0),
    [166] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ordered_list_marker, 1, 0, 0),
    [168] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(54),
    [170] = { .entry = { .count = 1, .reusable = true } },
    ACCEPT_INPUT(),
    [172] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(41),
    [174] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(29),
    [176] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(36),
    [178] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(49),
    [180] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(51),
    [182] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(22),
};

enum ts_external_scanner_symbol_identifiers {
    ts_external_token__eof = 0,
    ts_external_token_title_h0_marker = 1,
    ts_external_token_title_h1_marker = 2,
    ts_external_token_title_h2_marker = 3,
    ts_external_token_title_h3_marker = 4,
    ts_external_token_title_h4_marker = 5,
    ts_external_token_title_h5_marker = 6,
    ts_external_token_list_marker_star = 7,
    ts_external_token_list_marker_hyphen = 8,
    ts_external_token_list_marker_dot = 9,
    ts_external_token_list_marker_digit = 10,
    ts_external_token_list_marker_geek = 11,
    ts_external_token_list_marker_alpha = 12,
    ts_external_token_document_attr_marker = 13,
    ts_external_token_element_attr_marker = 14,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
    [ts_external_token__eof] = sym__eof,
    [ts_external_token_title_h0_marker] = sym_title_h0_marker,
    [ts_external_token_title_h1_marker] = sym_title_h1_marker,
    [ts_external_token_title_h2_marker] = sym_title_h2_marker,
    [ts_external_token_title_h3_marker] = sym_title_h3_marker,
    [ts_external_token_title_h4_marker] = sym_title_h4_marker,
    [ts_external_token_title_h5_marker] = sym_title_h5_marker,
    [ts_external_token_list_marker_star] = sym_list_marker_star,
    [ts_external_token_list_marker_hyphen] = sym_list_marker_hyphen,
    [ts_external_token_list_marker_dot] = sym_list_marker_dot,
    [ts_external_token_list_marker_digit] = sym_list_marker_digit,
    [ts_external_token_list_marker_geek] = sym_list_marker_geek,
    [ts_external_token_list_marker_alpha] = sym_list_marker_alpha,
    [ts_external_token_document_attr_marker] = sym_document_attr_marker,
    [ts_external_token_element_attr_marker] = sym_element_attr_marker,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
    [1] = {
        [ts_external_token__eof] = true,
        [ts_external_token_title_h0_marker] = true,
        [ts_external_token_title_h1_marker] = true,
        [ts_external_token_title_h2_marker] = true,
        [ts_external_token_title_h3_marker] = true,
        [ts_external_token_title_h4_marker] = true,
        [ts_external_token_title_h5_marker] = true,
        [ts_external_token_list_marker_star] = true,
        [ts_external_token_list_marker_hyphen] = true,
        [ts_external_token_list_marker_dot] = true,
        [ts_external_token_list_marker_digit] = true,
        [ts_external_token_list_marker_geek] = true,
        [ts_external_token_list_marker_alpha] = true,
        [ts_external_token_document_attr_marker] = true,
        [ts_external_token_element_attr_marker] = true,
    },
    [2] = {
        [ts_external_token_title_h0_marker] = true,
        [ts_external_token_title_h1_marker] = true,
        [ts_external_token_title_h2_marker] = true,
        [ts_external_token_title_h3_marker] = true,
        [ts_external_token_title_h4_marker] = true,
        [ts_external_token_title_h5_marker] = true,
        [ts_external_token_list_marker_star] = true,
        [ts_external_token_list_marker_hyphen] = true,
        [ts_external_token_list_marker_dot] = true,
        [ts_external_token_list_marker_digit] = true,
        [ts_external_token_list_marker_geek] = true,
        [ts_external_token_list_marker_alpha] = true,
        [ts_external_token_element_attr_marker] = true,
    },
    [3] = {
        [ts_external_token_list_marker_star] = true,
        [ts_external_token_list_marker_hyphen] = true,
        [ts_external_token_list_marker_dot] = true,
        [ts_external_token_list_marker_digit] = true,
        [ts_external_token_list_marker_geek] = true,
        [ts_external_token_list_marker_alpha] = true,
    },
    [4] = {
        [ts_external_token__eof] = true,
        [ts_external_token_list_marker_dot] = true,
        [ts_external_token_list_marker_digit] = true,
        [ts_external_token_list_marker_geek] = true,
        [ts_external_token_list_marker_alpha] = true,
    },
    [5] = {
        [ts_external_token__eof] = true,
        [ts_external_token_list_marker_star] = true,
        [ts_external_token_list_marker_hyphen] = true,
    },
    [6] = {
        [ts_external_token__eof] = true,
        [ts_external_token_document_attr_marker] = true,
    },
    [7] = {
        [ts_external_token__eof] = true,
    },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_asciidoc_external_scanner_create(void);
void tree_sitter_asciidoc_external_scanner_destroy(void *);
bool tree_sitter_asciidoc_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_asciidoc_external_scanner_serialize(void *, char *);
void tree_sitter_asciidoc_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_asciidoc(void) {
    static const TSLanguage language = {
        .version = LANGUAGE_VERSION,
        .symbol_count = SYMBOL_COUNT,
        .alias_count = ALIAS_COUNT,
        .token_count = TOKEN_COUNT,
        .external_token_count = EXTERNAL_TOKEN_COUNT,
        .state_count = STATE_COUNT,
        .large_state_count = LARGE_STATE_COUNT,
        .production_id_count = PRODUCTION_ID_COUNT,
        .field_count = FIELD_COUNT,
        .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
        .parse_table = &ts_parse_table[0][0],
        .small_parse_table = ts_small_parse_table,
        .small_parse_table_map = ts_small_parse_table_map,
        .parse_actions = ts_parse_actions,
        .symbol_names = ts_symbol_names,
        .symbol_metadata = ts_symbol_metadata,
        .public_symbol_map = ts_symbol_map,
        .alias_map = ts_non_terminal_alias_map,
        .alias_sequences = &ts_alias_sequences[0][0],
        .lex_modes = ts_lex_modes,
        .lex_fn = ts_lex,
        .external_scanner = {
            &ts_external_scanner_states[0][0],
            ts_external_scanner_symbol_map,
            tree_sitter_asciidoc_external_scanner_create,
            tree_sitter_asciidoc_external_scanner_destroy,
            tree_sitter_asciidoc_external_scanner_scan,
            tree_sitter_asciidoc_external_scanner_serialize,
            tree_sitter_asciidoc_external_scanner_deserialize,
        },
        .primary_state_ids = ts_primary_state_ids,
    };
    return &language;
}
#ifdef __cplusplus
}
#endif
