#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 53
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 14
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
    aux_sym_document_attr_token1 = 1,
    anon_sym_COLON = 2,
    anon_sym_LBRACK = 3,
    anon_sym_SPACE = 4,
    anon_sym_x = 5,
    anon_sym_STAR = 6,
    anon_sym_RBRACK = 7,
    aux_sym_line_token1 = 8,
    sym__NEWLINE = 9,
    sym__WHITE_SPACE = 10,
    sym__eof = 11,
    sym_title_h0_marker = 12,
    sym_title_h1_marker = 13,
    sym_title_h2_marker = 14,
    sym_title_h3_marker = 15,
    sym_title_h4_marker = 16,
    sym_title_h5_marker = 17,
    sym_list_marker_star = 18,
    sym_list_marker_hyphen = 19,
    sym_list_marker_dot = 20,
    sym_list_marker_digit = 21,
    sym_list_marker_geek = 22,
    sym_list_marker_alpha = 23,
    sym_document_attr_marker = 24,
    sym_document = 25,
    sym_title0 = 26,
    sym_title1 = 27,
    sym_title2 = 28,
    sym_title3 = 29,
    sym_title4 = 30,
    sym_title5 = 31,
    sym_document_attr = 32,
    sym_checked_list = 33,
    sym_unordered_list = 34,
    sym_ul_item = 35,
    sym_unordered_list_marker = 36,
    sym_ordered_list = 37,
    sym_ol_item = 38,
    sym_ordered_list_marker = 39,
    sym_line = 40,
    sym__block_end = 41,
    aux_sym_document_repeat1 = 42,
    aux_sym_title0_repeat1 = 43,
    aux_sym_checked_list_repeat1 = 44,
    aux_sym_ordered_list_repeat1 = 45,
};

static const char *const ts_symbol_names[] = {
    [ts_builtin_sym_end] = "end",
    [aux_sym_document_attr_token1] = "document_attr_token1",
    [anon_sym_COLON] = ":",
    [anon_sym_LBRACK] = "[",
    [anon_sym_SPACE] = " ",
    [anon_sym_x] = "x",
    [anon_sym_STAR] = "*",
    [anon_sym_RBRACK] = "]",
    [aux_sym_line_token1] = "line_token1",
    [sym__NEWLINE] = "_NEWLINE",
    [sym__WHITE_SPACE] = "_WHITE_SPACE",
    [sym__eof] = "_eof",
    [sym_title_h0_marker] = "title_h0_marker",
    [sym_title_h1_marker] = "title_h1_marker",
    [sym_title_h2_marker] = "title_h2_marker",
    [sym_title_h3_marker] = "title_h3_marker",
    [sym_title_h4_marker] = "title_h4_marker",
    [sym_title_h5_marker] = "title_h5_marker",
    [sym_list_marker_star] = "list_marker_star",
    [sym_list_marker_hyphen] = "list_marker_hyphen",
    [sym_list_marker_dot] = "list_marker_dot",
    [sym_list_marker_digit] = "list_marker_digit",
    [sym_list_marker_geek] = "list_marker_geek",
    [sym_list_marker_alpha] = "list_marker_alpha",
    [sym_document_attr_marker] = "document_attr_marker",
    [sym_document] = "document",
    [sym_title0] = "title0",
    [sym_title1] = "title1",
    [sym_title2] = "title2",
    [sym_title3] = "title3",
    [sym_title4] = "title4",
    [sym_title5] = "title5",
    [sym_document_attr] = "document_attr",
    [sym_checked_list] = "checked_list",
    [sym_unordered_list] = "unordered_list",
    [sym_ul_item] = "ul_item",
    [sym_unordered_list_marker] = "unordered_list_marker",
    [sym_ordered_list] = "ordered_list",
    [sym_ol_item] = "ol_item",
    [sym_ordered_list_marker] = "ordered_list_marker",
    [sym_line] = "line",
    [sym__block_end] = "_block_end",
    [aux_sym_document_repeat1] = "document_repeat1",
    [aux_sym_title0_repeat1] = "title0_repeat1",
    [aux_sym_checked_list_repeat1] = "checked_list_repeat1",
    [aux_sym_ordered_list_repeat1] = "ordered_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
    [ts_builtin_sym_end] = ts_builtin_sym_end,
    [aux_sym_document_attr_token1] = aux_sym_document_attr_token1,
    [anon_sym_COLON] = anon_sym_COLON,
    [anon_sym_LBRACK] = anon_sym_LBRACK,
    [anon_sym_SPACE] = anon_sym_SPACE,
    [anon_sym_x] = anon_sym_x,
    [anon_sym_STAR] = anon_sym_STAR,
    [anon_sym_RBRACK] = anon_sym_RBRACK,
    [aux_sym_line_token1] = aux_sym_line_token1,
    [sym__NEWLINE] = sym__NEWLINE,
    [sym__WHITE_SPACE] = sym__WHITE_SPACE,
    [sym__eof] = sym__eof,
    [sym_title_h0_marker] = sym_title_h0_marker,
    [sym_title_h1_marker] = sym_title_h1_marker,
    [sym_title_h2_marker] = sym_title_h2_marker,
    [sym_title_h3_marker] = sym_title_h3_marker,
    [sym_title_h4_marker] = sym_title_h4_marker,
    [sym_title_h5_marker] = sym_title_h5_marker,
    [sym_list_marker_star] = sym_list_marker_star,
    [sym_list_marker_hyphen] = sym_list_marker_hyphen,
    [sym_list_marker_dot] = sym_list_marker_dot,
    [sym_list_marker_digit] = sym_list_marker_digit,
    [sym_list_marker_geek] = sym_list_marker_geek,
    [sym_list_marker_alpha] = sym_list_marker_alpha,
    [sym_document_attr_marker] = sym_document_attr_marker,
    [sym_document] = sym_document,
    [sym_title0] = sym_title0,
    [sym_title1] = sym_title1,
    [sym_title2] = sym_title2,
    [sym_title3] = sym_title3,
    [sym_title4] = sym_title4,
    [sym_title5] = sym_title5,
    [sym_document_attr] = sym_document_attr,
    [sym_checked_list] = sym_checked_list,
    [sym_unordered_list] = sym_unordered_list,
    [sym_ul_item] = sym_ul_item,
    [sym_unordered_list_marker] = sym_unordered_list_marker,
    [sym_ordered_list] = sym_ordered_list,
    [sym_ol_item] = sym_ol_item,
    [sym_ordered_list_marker] = sym_ordered_list_marker,
    [sym_line] = sym_line,
    [sym__block_end] = sym__block_end,
    [aux_sym_document_repeat1] = aux_sym_document_repeat1,
    [aux_sym_title0_repeat1] = aux_sym_title0_repeat1,
    [aux_sym_checked_list_repeat1] = aux_sym_checked_list_repeat1,
    [aux_sym_ordered_list_repeat1] = aux_sym_ordered_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
    [ts_builtin_sym_end] = {
        .visible = false,
        .named = true,
    },
    [aux_sym_document_attr_token1] = {
        .visible = false,
        .named = false,
    },
    [anon_sym_COLON] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_LBRACK] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_SPACE] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_x] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_STAR] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_RBRACK] = {
        .visible = true,
        .named = false,
    },
    [aux_sym_line_token1] = {
        .visible = false,
        .named = false,
    },
    [sym__NEWLINE] = {
        .visible = false,
        .named = true,
    },
    [sym__WHITE_SPACE] = {
        .visible = false,
        .named = true,
    },
    [sym__eof] = {
        .visible = false,
        .named = true,
    },
    [sym_title_h0_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h1_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h2_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h3_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h4_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h5_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_star] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_hyphen] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_dot] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_digit] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_geek] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_alpha] = {
        .visible = true,
        .named = true,
    },
    [sym_document_attr_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_document] = {
        .visible = true,
        .named = true,
    },
    [sym_title0] = {
        .visible = true,
        .named = true,
    },
    [sym_title1] = {
        .visible = true,
        .named = true,
    },
    [sym_title2] = {
        .visible = true,
        .named = true,
    },
    [sym_title3] = {
        .visible = true,
        .named = true,
    },
    [sym_title4] = {
        .visible = true,
        .named = true,
    },
    [sym_title5] = {
        .visible = true,
        .named = true,
    },
    [sym_document_attr] = {
        .visible = true,
        .named = true,
    },
    [sym_checked_list] = {
        .visible = true,
        .named = true,
    },
    [sym_unordered_list] = {
        .visible = true,
        .named = true,
    },
    [sym_ul_item] = {
        .visible = true,
        .named = true,
    },
    [sym_unordered_list_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_ordered_list] = {
        .visible = true,
        .named = true,
    },
    [sym_ol_item] = {
        .visible = true,
        .named = true,
    },
    [sym_ordered_list_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_line] = {
        .visible = true,
        .named = true,
    },
    [sym__block_end] = {
        .visible = false,
        .named = true,
    },
    [aux_sym_document_repeat1] = {
        .visible = false,
        .named = false,
    },
    [aux_sym_title0_repeat1] = {
        .visible = false,
        .named = false,
    },
    [aux_sym_checked_list_repeat1] = {
        .visible = false,
        .named = false,
    },
    [aux_sym_ordered_list_repeat1] = {
        .visible = false,
        .named = false,
    },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
    [0] = { 0 },
};

static const uint16_t ts_non_terminal_alias_map[] = {
    0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
    [0] = 0,
    [1] = 1,
    [2] = 2,
    [3] = 3,
    [4] = 4,
    [5] = 5,
    [6] = 6,
    [7] = 7,
    [8] = 8,
    [9] = 9,
    [10] = 10,
    [11] = 11,
    [12] = 12,
    [13] = 13,
    [14] = 14,
    [15] = 15,
    [16] = 16,
    [17] = 17,
    [18] = 4,
    [19] = 19,
    [20] = 20,
    [21] = 21,
    [22] = 22,
    [23] = 23,
    [24] = 4,
    [25] = 25,
    [26] = 26,
    [27] = 27,
    [28] = 28,
    [29] = 28,
    [30] = 30,
    [31] = 28,
    [32] = 32,
    [33] = 33,
    [34] = 4,
    [35] = 28,
    [36] = 36,
    [37] = 37,
    [38] = 38,
    [39] = 39,
    [40] = 40,
    [41] = 41,
    [42] = 42,
    [43] = 43,
    [44] = 44,
    [45] = 45,
    [46] = 46,
    [47] = 47,
    [48] = 48,
    [49] = 49,
    [50] = 50,
    [51] = 51,
    [52] = 52,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
    START_LEXER();
    eof = lexer->eof(lexer);
    switch(state) {
        case 0:
            if(eof)
                ADVANCE(4);
            ADVANCE_MAP(
                '\t', 15,
                '\n', 14,
                '\r', 1,
                ' ', 8,
                '*', 10,
                ':', 6,
                '[', 7,
                ']', 11,
                'x', 9,
            );
            if(('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(5);
            END_STATE();
        case 1:
            if(lookahead == '\n')
                ADVANCE(14);
            END_STATE();
        case 2:
            if(lookahead == '\n')
                ADVANCE(14);
            if(lookahead == '\r')
                ADVANCE(1);
            if(lookahead == '\t' ||
               lookahead == ' ')
                ADVANCE(15);
            if(('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(5);
            END_STATE();
        case 3:
            if(lookahead == '\n')
                ADVANCE(14);
            if(lookahead == '\r')
                ADVANCE(12);
            if(lookahead != 0)
                ADVANCE(13);
            END_STATE();
        case 4:
            ACCEPT_TOKEN(ts_builtin_sym_end);
            END_STATE();
        case 5:
            ACCEPT_TOKEN(aux_sym_document_attr_token1);
            if(lookahead == '-' ||
               ('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(5);
            END_STATE();
        case 6:
            ACCEPT_TOKEN(anon_sym_COLON);
            END_STATE();
        case 7:
            ACCEPT_TOKEN(anon_sym_LBRACK);
            END_STATE();
        case 8:
            ACCEPT_TOKEN(anon_sym_SPACE);
            if(lookahead == '\t' ||
               lookahead == ' ')
                ADVANCE(15);
            END_STATE();
        case 9:
            ACCEPT_TOKEN(anon_sym_x);
            if(lookahead == '-' ||
               ('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(5);
            END_STATE();
        case 10:
            ACCEPT_TOKEN(anon_sym_STAR);
            END_STATE();
        case 11:
            ACCEPT_TOKEN(anon_sym_RBRACK);
            END_STATE();
        case 12:
            ACCEPT_TOKEN(aux_sym_line_token1);
            if(lookahead == '\n')
                ADVANCE(14);
            if(lookahead != 0)
                ADVANCE(13);
            END_STATE();
        case 13:
            ACCEPT_TOKEN(aux_sym_line_token1);
            if(lookahead != 0 &&
               lookahead != '\n')
                ADVANCE(13);
            END_STATE();
        case 14:
            ACCEPT_TOKEN(sym__NEWLINE);
            END_STATE();
        case 15:
            ACCEPT_TOKEN(sym__WHITE_SPACE);
            if(lookahead == '\t' ||
               lookahead == ' ')
                ADVANCE(15);
            END_STATE();
        default:
            return false;
    }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
    [0] = { .lex_state = 0, .external_lex_state = 1 },
    [1] = { .lex_state = 0, .external_lex_state = 2 },
    [2] = { .lex_state = 0, .external_lex_state = 2 },
    [3] = { .lex_state = 0, .external_lex_state = 2 },
    [4] = { .lex_state = 0, .external_lex_state = 2 },
    [5] = { .lex_state = 0, .external_lex_state = 2 },
    [6] = { .lex_state = 0, .external_lex_state = 2 },
    [7] = { .lex_state = 0, .external_lex_state = 2 },
    [8] = { .lex_state = 0, .external_lex_state = 2 },
    [9] = { .lex_state = 0, .external_lex_state = 2 },
    [10] = { .lex_state = 0, .external_lex_state = 2 },
    [11] = { .lex_state = 0, .external_lex_state = 2 },
    [12] = { .lex_state = 0, .external_lex_state = 2 },
    [13] = { .lex_state = 0, .external_lex_state = 2 },
    [14] = { .lex_state = 0, .external_lex_state = 3 },
    [15] = { .lex_state = 0, .external_lex_state = 3 },
    [16] = { .lex_state = 0, .external_lex_state = 4 },
    [17] = { .lex_state = 0, .external_lex_state = 4 },
    [18] = { .lex_state = 0, .external_lex_state = 3 },
    [19] = { .lex_state = 0, .external_lex_state = 5 },
    [20] = { .lex_state = 0, .external_lex_state = 3 },
    [21] = { .lex_state = 0, .external_lex_state = 5 },
    [22] = { .lex_state = 0, .external_lex_state = 5 },
    [23] = { .lex_state = 0, .external_lex_state = 4 },
    [24] = { .lex_state = 0, .external_lex_state = 4 },
    [25] = { .lex_state = 3 },
    [26] = { .lex_state = 3 },
    [27] = { .lex_state = 3 },
    [28] = { .lex_state = 0, .external_lex_state = 6 },
    [29] = { .lex_state = 0, .external_lex_state = 6 },
    [30] = { .lex_state = 3 },
    [31] = { .lex_state = 0, .external_lex_state = 6 },
    [32] = { .lex_state = 3 },
    [33] = { .lex_state = 3 },
    [34] = { .lex_state = 0, .external_lex_state = 5 },
    [35] = { .lex_state = 0, .external_lex_state = 6 },
    [36] = { .lex_state = 0, .external_lex_state = 5 },
    [37] = { .lex_state = 3 },
    [38] = { .lex_state = 3 },
    [39] = { .lex_state = 3 },
    [40] = { .lex_state = 0 },
    [41] = { .lex_state = 2 },
    [42] = { .lex_state = 0 },
    [43] = { .lex_state = 2 },
    [44] = { .lex_state = 2 },
    [45] = { .lex_state = 2 },
    [46] = { .lex_state = 2 },
    [47] = { .lex_state = 2 },
    [48] = { .lex_state = 2 },
    [49] = { .lex_state = 2 },
    [50] = { .lex_state = 2 },
    [51] = { .lex_state = 2 },
    [52] = { .lex_state = 2 },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
    [0] = {
        [ts_builtin_sym_end] = ACTIONS(1),
        [aux_sym_document_attr_token1] = ACTIONS(1),
        [anon_sym_COLON] = ACTIONS(1),
        [anon_sym_LBRACK] = ACTIONS(1),
        [anon_sym_SPACE] = ACTIONS(1),
        [anon_sym_x] = ACTIONS(1),
        [anon_sym_STAR] = ACTIONS(1),
        [anon_sym_RBRACK] = ACTIONS(1),
        [sym__NEWLINE] = ACTIONS(3),
        [sym__WHITE_SPACE] = ACTIONS(1),
        [sym__eof] = ACTIONS(1),
        [sym_title_h0_marker] = ACTIONS(1),
        [sym_title_h1_marker] = ACTIONS(1),
        [sym_title_h2_marker] = ACTIONS(1),
        [sym_title_h3_marker] = ACTIONS(1),
        [sym_title_h4_marker] = ACTIONS(1),
        [sym_title_h5_marker] = ACTIONS(1),
        [sym_list_marker_star] = ACTIONS(1),
        [sym_list_marker_hyphen] = ACTIONS(1),
        [sym_list_marker_dot] = ACTIONS(1),
        [sym_list_marker_digit] = ACTIONS(1),
        [sym_list_marker_geek] = ACTIONS(1),
        [sym_list_marker_alpha] = ACTIONS(1),
        [sym_document_attr_marker] = ACTIONS(1),
    },
    [1] = {
        [sym_document] = STATE(40),
        [sym_title0] = STATE(3),
        [sym_title1] = STATE(3),
        [sym_title2] = STATE(3),
        [sym_title3] = STATE(3),
        [sym_title4] = STATE(3),
        [sym_title5] = STATE(3),
        [sym_checked_list] = STATE(3),
        [sym_unordered_list] = STATE(3),
        [sym_ul_item] = STATE(16),
        [sym_unordered_list_marker] = STATE(51),
        [sym_ordered_list] = STATE(3),
        [sym_ol_item] = STATE(14),
        [sym_ordered_list_marker] = STATE(45),
        [aux_sym_document_repeat1] = STATE(3),
        [aux_sym_checked_list_repeat1] = STATE(16),
        [aux_sym_ordered_list_repeat1] = STATE(14),
        [ts_builtin_sym_end] = ACTIONS(5),
        [sym__NEWLINE] = ACTIONS(3),
        [sym_title_h0_marker] = ACTIONS(7),
        [sym_title_h1_marker] = ACTIONS(9),
        [sym_title_h2_marker] = ACTIONS(11),
        [sym_title_h3_marker] = ACTIONS(13),
        [sym_title_h4_marker] = ACTIONS(15),
        [sym_title_h5_marker] = ACTIONS(17),
        [sym_list_marker_star] = ACTIONS(19),
        [sym_list_marker_hyphen] = ACTIONS(19),
        [sym_list_marker_dot] = ACTIONS(21),
        [sym_list_marker_digit] = ACTIONS(21),
        [sym_list_marker_geek] = ACTIONS(21),
        [sym_list_marker_alpha] = ACTIONS(21),
    },
    [2] = {
        [sym_title0] = STATE(2),
        [sym_title1] = STATE(2),
        [sym_title2] = STATE(2),
        [sym_title3] = STATE(2),
        [sym_title4] = STATE(2),
        [sym_title5] = STATE(2),
        [sym_checked_list] = STATE(2),
        [sym_unordered_list] = STATE(2),
        [sym_ul_item] = STATE(16),
        [sym_unordered_list_marker] = STATE(51),
        [sym_ordered_list] = STATE(2),
        [sym_ol_item] = STATE(14),
        [sym_ordered_list_marker] = STATE(45),
        [aux_sym_document_repeat1] = STATE(2),
        [aux_sym_checked_list_repeat1] = STATE(16),
        [aux_sym_ordered_list_repeat1] = STATE(14),
        [ts_builtin_sym_end] = ACTIONS(23),
        [sym__NEWLINE] = ACTIONS(3),
        [sym_title_h0_marker] = ACTIONS(25),
        [sym_title_h1_marker] = ACTIONS(28),
        [sym_title_h2_marker] = ACTIONS(31),
        [sym_title_h3_marker] = ACTIONS(34),
        [sym_title_h4_marker] = ACTIONS(37),
        [sym_title_h5_marker] = ACTIONS(40),
        [sym_list_marker_star] = ACTIONS(43),
        [sym_list_marker_hyphen] = ACTIONS(43),
        [sym_list_marker_dot] = ACTIONS(46),
        [sym_list_marker_digit] = ACTIONS(46),
        [sym_list_marker_geek] = ACTIONS(46),
        [sym_list_marker_alpha] = ACTIONS(46),
    },
    [3] = {
        [sym_title0] = STATE(2),
        [sym_title1] = STATE(2),
        [sym_title2] = STATE(2),
        [sym_title3] = STATE(2),
        [sym_title4] = STATE(2),
        [sym_title5] = STATE(2),
        [sym_checked_list] = STATE(2),
        [sym_unordered_list] = STATE(2),
        [sym_ul_item] = STATE(16),
        [sym_unordered_list_marker] = STATE(51),
        [sym_ordered_list] = STATE(2),
        [sym_ol_item] = STATE(14),
        [sym_ordered_list_marker] = STATE(45),
        [aux_sym_document_repeat1] = STATE(2),
        [aux_sym_checked_list_repeat1] = STATE(16),
        [aux_sym_ordered_list_repeat1] = STATE(14),
        [ts_builtin_sym_end] = ACTIONS(49),
        [sym__NEWLINE] = ACTIONS(3),
        [sym_title_h0_marker] = ACTIONS(7),
        [sym_title_h1_marker] = ACTIONS(9),
        [sym_title_h2_marker] = ACTIONS(11),
        [sym_title_h3_marker] = ACTIONS(13),
        [sym_title_h4_marker] = ACTIONS(15),
        [sym_title_h5_marker] = ACTIONS(17),
        [sym_list_marker_star] = ACTIONS(19),
        [sym_list_marker_hyphen] = ACTIONS(19),
        [sym_list_marker_dot] = ACTIONS(21),
        [sym_list_marker_digit] = ACTIONS(21),
        [sym_list_marker_geek] = ACTIONS(21),
        [sym_list_marker_alpha] = ACTIONS(21),
    },
};

static const uint16_t ts_small_parse_table[] = {
    [0] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(51),
    13,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    ts_builtin_sym_end,
    [19] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(53),
    13,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    ts_builtin_sym_end,
    [38] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(55),
    13,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    ts_builtin_sym_end,
    [57] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(57),
    13,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    ts_builtin_sym_end,
    [76] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(59),
    13,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    ts_builtin_sym_end,
    [95] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(61),
    13,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    ts_builtin_sym_end,
    [114] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(63),
    13,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    ts_builtin_sym_end,
    [133] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(65),
    13,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    ts_builtin_sym_end,
    [152] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(67),
    13,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    ts_builtin_sym_end,
    [171] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(69),
    13,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    ts_builtin_sym_end,
    [190] = 5,
    STATE(12),
    1,
    sym__block_end,
    STATE(45),
    1,
    sym_ordered_list_marker,
    ACTIONS(71),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(15),
    2,
    sym_ol_item,
    aux_sym_ordered_list_repeat1,
    ACTIONS(21),
    4,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    [211] = 4,
    STATE(45),
    1,
    sym_ordered_list_marker,
    ACTIONS(73),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(15),
    2,
    sym_ol_item,
    aux_sym_ordered_list_repeat1,
    ACTIONS(75),
    4,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    [229] = 5,
    STATE(13),
    1,
    sym__block_end,
    STATE(51),
    1,
    sym_unordered_list_marker,
    ACTIONS(19),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    ACTIONS(78),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(17),
    2,
    sym_ul_item,
    aux_sym_checked_list_repeat1,
    [248] = 4,
    STATE(51),
    1,
    sym_unordered_list_marker,
    ACTIONS(80),
    2,
    sym__eof,
    sym__NEWLINE,
    ACTIONS(82),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    STATE(17),
    2,
    sym_ul_item,
    aux_sym_checked_list_repeat1,
    [264] = 1,
    ACTIONS(51),
    6,
    sym__eof,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym__NEWLINE,
    [273] = 4,
    ACTIONS(87),
    1,
    sym_document_attr_marker,
    STATE(5),
    1,
    sym__block_end,
    ACTIONS(85),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(22),
    2,
    sym_document_attr,
    aux_sym_title0_repeat1,
    [288] = 1,
    ACTIONS(89),
    6,
    sym__eof,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym__NEWLINE,
    [297] = 4,
    ACTIONS(87),
    1,
    sym_document_attr_marker,
    STATE(6),
    1,
    sym__block_end,
    ACTIONS(91),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(19),
    2,
    sym_document_attr,
    aux_sym_title0_repeat1,
    [312] = 3,
    ACTIONS(95),
    1,
    sym_document_attr_marker,
    ACTIONS(93),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(22),
    2,
    sym_document_attr,
    aux_sym_title0_repeat1,
    [324] = 1,
    ACTIONS(98),
    4,
    sym__eof,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym__NEWLINE,
    [331] = 1,
    ACTIONS(51),
    4,
    sym__eof,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym__NEWLINE,
    [338] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(100),
    1,
    aux_sym_line_token1,
    STATE(11),
    1,
    sym_line,
    [348] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(100),
    1,
    aux_sym_line_token1,
    STATE(9),
    1,
    sym_line,
    [358] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(102),
    1,
    aux_sym_line_token1,
    STATE(20),
    1,
    sym_line,
    [368] = 2,
    STATE(18),
    1,
    sym__block_end,
    ACTIONS(104),
    2,
    sym__eof,
    sym__NEWLINE,
    [376] = 2,
    STATE(24),
    1,
    sym__block_end,
    ACTIONS(106),
    2,
    sym__eof,
    sym__NEWLINE,
    [384] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(100),
    1,
    aux_sym_line_token1,
    STATE(10),
    1,
    sym_line,
    [394] = 2,
    STATE(34),
    1,
    sym__block_end,
    ACTIONS(108),
    2,
    sym__eof,
    sym__NEWLINE,
    [402] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(100),
    1,
    aux_sym_line_token1,
    STATE(8),
    1,
    sym_line,
    [412] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(100),
    1,
    aux_sym_line_token1,
    STATE(7),
    1,
    sym_line,
    [422] = 1,
    ACTIONS(51),
    3,
    sym__eof,
    sym_document_attr_marker,
    sym__NEWLINE,
    [428] = 2,
    STATE(4),
    1,
    sym__block_end,
    ACTIONS(110),
    2,
    sym__eof,
    sym__NEWLINE,
    [436] = 1,
    ACTIONS(112),
    3,
    sym__eof,
    sym_document_attr_marker,
    sym__NEWLINE,
    [442] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(114),
    1,
    aux_sym_line_token1,
    STATE(23),
    1,
    sym_line,
    [452] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(116),
    1,
    aux_sym_line_token1,
    STATE(36),
    1,
    sym_line,
    [462] = 3,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(116),
    1,
    aux_sym_line_token1,
    STATE(21),
    1,
    sym_line,
    [472] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(118),
    1,
    ts_builtin_sym_end,
    [479] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(120),
    1,
    sym__WHITE_SPACE,
    [486] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(122),
    1,
    anon_sym_COLON,
    [493] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(124),
    1,
    sym__WHITE_SPACE,
    [500] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(126),
    1,
    sym__WHITE_SPACE,
    [507] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    sym__WHITE_SPACE,
    [514] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(130),
    1,
    sym__WHITE_SPACE,
    [521] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(132),
    1,
    sym__WHITE_SPACE,
    [528] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(134),
    1,
    sym__WHITE_SPACE,
    [535] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(136),
    1,
    sym__WHITE_SPACE,
    [542] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(138),
    1,
    sym__WHITE_SPACE,
    [549] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(140),
    1,
    sym__WHITE_SPACE,
    [556] = 2,
    ACTIONS(3),
    1,
    sym__NEWLINE,
    ACTIONS(142),
    1,
    aux_sym_document_attr_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
    [SMALL_STATE(4)] = 0,
    [SMALL_STATE(5)] = 19,
    [SMALL_STATE(6)] = 38,
    [SMALL_STATE(7)] = 57,
    [SMALL_STATE(8)] = 76,
    [SMALL_STATE(9)] = 95,
    [SMALL_STATE(10)] = 114,
    [SMALL_STATE(11)] = 133,
    [SMALL_STATE(12)] = 152,
    [SMALL_STATE(13)] = 171,
    [SMALL_STATE(14)] = 190,
    [SMALL_STATE(15)] = 211,
    [SMALL_STATE(16)] = 229,
    [SMALL_STATE(17)] = 248,
    [SMALL_STATE(18)] = 264,
    [SMALL_STATE(19)] = 273,
    [SMALL_STATE(20)] = 288,
    [SMALL_STATE(21)] = 297,
    [SMALL_STATE(22)] = 312,
    [SMALL_STATE(23)] = 324,
    [SMALL_STATE(24)] = 331,
    [SMALL_STATE(25)] = 338,
    [SMALL_STATE(26)] = 348,
    [SMALL_STATE(27)] = 358,
    [SMALL_STATE(28)] = 368,
    [SMALL_STATE(29)] = 376,
    [SMALL_STATE(30)] = 384,
    [SMALL_STATE(31)] = 394,
    [SMALL_STATE(32)] = 402,
    [SMALL_STATE(33)] = 412,
    [SMALL_STATE(34)] = 422,
    [SMALL_STATE(35)] = 428,
    [SMALL_STATE(36)] = 436,
    [SMALL_STATE(37)] = 442,
    [SMALL_STATE(38)] = 452,
    [SMALL_STATE(39)] = 462,
    [SMALL_STATE(40)] = 472,
    [SMALL_STATE(41)] = 479,
    [SMALL_STATE(42)] = 486,
    [SMALL_STATE(43)] = 493,
    [SMALL_STATE(44)] = 500,
    [SMALL_STATE(45)] = 507,
    [SMALL_STATE(46)] = 514,
    [SMALL_STATE(47)] = 521,
    [SMALL_STATE(48)] = 528,
    [SMALL_STATE(49)] = 535,
    [SMALL_STATE(50)] = 542,
    [SMALL_STATE(51)] = 549,
    [SMALL_STATE(52)] = 556,
};

static const TSParseActionEntry ts_parse_actions[] = {
    [0] = { .entry = { .count = 0, .reusable = false } },
    [1] = { .entry = { .count = 1, .reusable = false } },
    RECOVER(),
    [3] = { .entry = { .count = 1, .reusable = true } },
    SHIFT_EXTRA(),
    [5] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_document, 0, 0, 0),
    [7] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(44),
    [9] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(46),
    [11] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(43),
    [13] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(41),
    [15] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(47),
    [17] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(48),
    [19] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(49),
    [21] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(50),
    [23] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    [25] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(44),
    [28] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(46),
    [31] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(43),
    [34] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(41),
    [37] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(47),
    [40] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(48),
    [43] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(49),
    [46] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(50),
    [49] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_document, 1, 0, 0),
    [51] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_line, 2, 0, 0),
    [53] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title0, 5, 0, 0),
    [55] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title0, 4, 0, 0),
    [57] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title5, 3, 0, 0),
    [59] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title4, 3, 0, 0),
    [61] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title3, 3, 0, 0),
    [63] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title2, 3, 0, 0),
    [65] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title1, 3, 0, 0),
    [67] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ordered_list, 2, 0, 0),
    [69] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_checked_list, 2, 0, 0),
    [71] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(12),
    [73] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_ordered_list_repeat1, 2, 0, 0),
    [75] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_ordered_list_repeat1, 2, 0, 0),
    SHIFT_REPEAT(50),
    [78] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(13),
    [80] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_checked_list_repeat1, 2, 0, 0),
    [82] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_checked_list_repeat1, 2, 0, 0),
    SHIFT_REPEAT(49),
    [85] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(5),
    [87] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(52),
    [89] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ol_item, 3, 0, 0),
    [91] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(6),
    [93] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_title0_repeat1, 2, 0, 0),
    [95] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_title0_repeat1, 2, 0, 0),
    SHIFT_REPEAT(52),
    [98] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ul_item, 3, 0, 0),
    [100] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(35),
    [102] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(28),
    [104] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(18),
    [106] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(24),
    [108] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(34),
    [110] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(4),
    [112] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_document_attr, 4, 0, 0),
    [114] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(29),
    [116] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(31),
    [118] = { .entry = { .count = 1, .reusable = true } },
    ACCEPT_INPUT(),
    [120] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(26),
    [122] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(38),
    [124] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(30),
    [126] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(39),
    [128] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(27),
    [130] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(25),
    [132] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(32),
    [134] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(33),
    [136] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_unordered_list_marker, 1, 0, 0),
    [138] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ordered_list_marker, 1, 0, 0),
    [140] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(37),
    [142] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(42),
};

enum ts_external_scanner_symbol_identifiers {
    ts_external_token__eof = 0,
    ts_external_token_title_h0_marker = 1,
    ts_external_token_title_h1_marker = 2,
    ts_external_token_title_h2_marker = 3,
    ts_external_token_title_h3_marker = 4,
    ts_external_token_title_h4_marker = 5,
    ts_external_token_title_h5_marker = 6,
    ts_external_token_list_marker_star = 7,
    ts_external_token_list_marker_hyphen = 8,
    ts_external_token_list_marker_dot = 9,
    ts_external_token_list_marker_digit = 10,
    ts_external_token_list_marker_geek = 11,
    ts_external_token_list_marker_alpha = 12,
    ts_external_token_document_attr_marker = 13,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
    [ts_external_token__eof] = sym__eof,
    [ts_external_token_title_h0_marker] = sym_title_h0_marker,
    [ts_external_token_title_h1_marker] = sym_title_h1_marker,
    [ts_external_token_title_h2_marker] = sym_title_h2_marker,
    [ts_external_token_title_h3_marker] = sym_title_h3_marker,
    [ts_external_token_title_h4_marker] = sym_title_h4_marker,
    [ts_external_token_title_h5_marker] = sym_title_h5_marker,
    [ts_external_token_list_marker_star] = sym_list_marker_star,
    [ts_external_token_list_marker_hyphen] = sym_list_marker_hyphen,
    [ts_external_token_list_marker_dot] = sym_list_marker_dot,
    [ts_external_token_list_marker_digit] = sym_list_marker_digit,
    [ts_external_token_list_marker_geek] = sym_list_marker_geek,
    [ts_external_token_list_marker_alpha] = sym_list_marker_alpha,
    [ts_external_token_document_attr_marker] = sym_document_attr_marker,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
    [1] = {
        [ts_external_token__eof] = true,
        [ts_external_token_title_h0_marker] = true,
        [ts_external_token_title_h1_marker] = true,
        [ts_external_token_title_h2_marker] = true,
        [ts_external_token_title_h3_marker] = true,
        [ts_external_token_title_h4_marker] = true,
        [ts_external_token_title_h5_marker] = true,
        [ts_external_token_list_marker_star] = true,
        [ts_external_token_list_marker_hyphen] = true,
        [ts_external_token_list_marker_dot] = true,
        [ts_external_token_list_marker_digit] = true,
        [ts_external_token_list_marker_geek] = true,
        [ts_external_token_list_marker_alpha] = true,
        [ts_external_token_document_attr_marker] = true,
    },
    [2] = {
        [ts_external_token_title_h0_marker] = true,
        [ts_external_token_title_h1_marker] = true,
        [ts_external_token_title_h2_marker] = true,
        [ts_external_token_title_h3_marker] = true,
        [ts_external_token_title_h4_marker] = true,
        [ts_external_token_title_h5_marker] = true,
        [ts_external_token_list_marker_star] = true,
        [ts_external_token_list_marker_hyphen] = true,
        [ts_external_token_list_marker_dot] = true,
        [ts_external_token_list_marker_digit] = true,
        [ts_external_token_list_marker_geek] = true,
        [ts_external_token_list_marker_alpha] = true,
    },
    [3] = {
        [ts_external_token__eof] = true,
        [ts_external_token_list_marker_dot] = true,
        [ts_external_token_list_marker_digit] = true,
        [ts_external_token_list_marker_geek] = true,
        [ts_external_token_list_marker_alpha] = true,
    },
    [4] = {
        [ts_external_token__eof] = true,
        [ts_external_token_list_marker_star] = true,
        [ts_external_token_list_marker_hyphen] = true,
    },
    [5] = {
        [ts_external_token__eof] = true,
        [ts_external_token_document_attr_marker] = true,
    },
    [6] = {
        [ts_external_token__eof] = true,
    },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_asciidoc_external_scanner_create(void);
void tree_sitter_asciidoc_external_scanner_destroy(void *);
bool tree_sitter_asciidoc_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_asciidoc_external_scanner_serialize(void *, char *);
void tree_sitter_asciidoc_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_asciidoc(void) {
    static const TSLanguage language = {
        .version = LANGUAGE_VERSION,
        .symbol_count = SYMBOL_COUNT,
        .alias_count = ALIAS_COUNT,
        .token_count = TOKEN_COUNT,
        .external_token_count = EXTERNAL_TOKEN_COUNT,
        .state_count = STATE_COUNT,
        .large_state_count = LARGE_STATE_COUNT,
        .production_id_count = PRODUCTION_ID_COUNT,
        .field_count = FIELD_COUNT,
        .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
        .parse_table = &ts_parse_table[0][0],
        .small_parse_table = ts_small_parse_table,
        .small_parse_table_map = ts_small_parse_table_map,
        .parse_actions = ts_parse_actions,
        .symbol_names = ts_symbol_names,
        .symbol_metadata = ts_symbol_metadata,
        .public_symbol_map = ts_symbol_map,
        .alias_map = ts_non_terminal_alias_map,
        .alias_sequences = &ts_alias_sequences[0][0],
        .lex_modes = ts_lex_modes,
        .lex_fn = ts_lex,
        .external_scanner = {
            &ts_external_scanner_states[0][0],
            ts_external_scanner_symbol_map,
            tree_sitter_asciidoc_external_scanner_create,
            tree_sitter_asciidoc_external_scanner_destroy,
            tree_sitter_asciidoc_external_scanner_scan,
            tree_sitter_asciidoc_external_scanner_serialize,
            tree_sitter_asciidoc_external_scanner_deserialize,
        },
        .primary_state_ids = ts_primary_state_ids,
    };
    return &language;
}
#ifdef __cplusplus
}
#endif
