#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 83
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 55
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 15
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
    aux_sym_document_attr_token1 = 1,
    anon_sym_COLON = 2,
    aux_sym_element_attr_token1 = 3,
    anon_sym_RBRACK = 4,
    anon_sym_LBRACK = 5,
    anon_sym_SPACE = 6,
    anon_sym_x = 7,
    anon_sym_STAR = 8,
    aux_sym_line_token1 = 9,
    anon_sym_SLASH_SLASH = 10,
    aux_sym_comment_token1 = 11,
    sym__NEWLINE = 12,
    sym__WHITE_SPACE = 13,
    sym__eof = 14,
    sym_title_h0_marker = 15,
    sym_title_h1_marker = 16,
    sym_title_h2_marker = 17,
    sym_title_h3_marker = 18,
    sym_title_h4_marker = 19,
    sym_title_h5_marker = 20,
    sym_list_marker_star = 21,
    sym_list_marker_hyphen = 22,
    sym_list_marker_dot = 23,
    sym_list_marker_digit = 24,
    sym_list_marker_geek = 25,
    sym_list_marker_alpha = 26,
    sym_document_attr_marker = 27,
    sym_element_attr_marker = 28,
    sym_document = 29,
    sym__section_block = 30,
    sym_title0 = 31,
    sym_title1 = 32,
    sym_title2 = 33,
    sym_title3 = 34,
    sym_title4 = 35,
    sym_title5 = 36,
    sym_document_attr = 37,
    sym_element_attr = 38,
    sym_checked_list = 39,
    sym_ck_item = 40,
    sym_unordered_list = 41,
    sym_ul_item = 42,
    sym_unordered_list_marker = 43,
    sym_ordered_list = 44,
    sym_ol_item = 45,
    sym_ordered_list_marker = 46,
    sym_line = 47,
    sym_comment = 48,
    sym__block_end = 49,
    aux_sym_document_repeat1 = 50,
    aux_sym_title0_repeat1 = 51,
    aux_sym_checked_list_repeat1 = 52,
    aux_sym_unordered_list_repeat1 = 53,
    aux_sym_ordered_list_repeat1 = 54,
};

static const char *const ts_symbol_names[] = {
    [ts_builtin_sym_end] = "end",
    [aux_sym_document_attr_token1] = "document_attr_token1",
    [anon_sym_COLON] = ":",
    [aux_sym_element_attr_token1] = "element_attr_token1",
    [anon_sym_RBRACK] = "]",
    [anon_sym_LBRACK] = "[",
    [anon_sym_SPACE] = " ",
    [anon_sym_x] = "x",
    [anon_sym_STAR] = "*",
    [aux_sym_line_token1] = "line_token1",
    [anon_sym_SLASH_SLASH] = "//",
    [aux_sym_comment_token1] = "comment_token1",
    [sym__NEWLINE] = "_NEWLINE",
    [sym__WHITE_SPACE] = "_WHITE_SPACE",
    [sym__eof] = "_eof",
    [sym_title_h0_marker] = "title_h0_marker",
    [sym_title_h1_marker] = "title_h1_marker",
    [sym_title_h2_marker] = "title_h2_marker",
    [sym_title_h3_marker] = "title_h3_marker",
    [sym_title_h4_marker] = "title_h4_marker",
    [sym_title_h5_marker] = "title_h5_marker",
    [sym_list_marker_star] = "list_marker_star",
    [sym_list_marker_hyphen] = "list_marker_hyphen",
    [sym_list_marker_dot] = "list_marker_dot",
    [sym_list_marker_digit] = "list_marker_digit",
    [sym_list_marker_geek] = "list_marker_geek",
    [sym_list_marker_alpha] = "list_marker_alpha",
    [sym_document_attr_marker] = "document_attr_marker",
    [sym_element_attr_marker] = "element_attr_marker",
    [sym_document] = "document",
    [sym__section_block] = "_section_block",
    [sym_title0] = "title0",
    [sym_title1] = "title1",
    [sym_title2] = "title2",
    [sym_title3] = "title3",
    [sym_title4] = "title4",
    [sym_title5] = "title5",
    [sym_document_attr] = "document_attr",
    [sym_element_attr] = "element_attr",
    [sym_checked_list] = "checked_list",
    [sym_ck_item] = "ck_item",
    [sym_unordered_list] = "unordered_list",
    [sym_ul_item] = "ul_item",
    [sym_unordered_list_marker] = "unordered_list_marker",
    [sym_ordered_list] = "ordered_list",
    [sym_ol_item] = "ol_item",
    [sym_ordered_list_marker] = "ordered_list_marker",
    [sym_line] = "line",
    [sym_comment] = "comment",
    [sym__block_end] = "_block_end",
    [aux_sym_document_repeat1] = "document_repeat1",
    [aux_sym_title0_repeat1] = "title0_repeat1",
    [aux_sym_checked_list_repeat1] = "checked_list_repeat1",
    [aux_sym_unordered_list_repeat1] = "unordered_list_repeat1",
    [aux_sym_ordered_list_repeat1] = "ordered_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
    [ts_builtin_sym_end] = ts_builtin_sym_end,
    [aux_sym_document_attr_token1] = aux_sym_document_attr_token1,
    [anon_sym_COLON] = anon_sym_COLON,
    [aux_sym_element_attr_token1] = aux_sym_element_attr_token1,
    [anon_sym_RBRACK] = anon_sym_RBRACK,
    [anon_sym_LBRACK] = anon_sym_LBRACK,
    [anon_sym_SPACE] = anon_sym_SPACE,
    [anon_sym_x] = anon_sym_x,
    [anon_sym_STAR] = anon_sym_STAR,
    [aux_sym_line_token1] = aux_sym_line_token1,
    [anon_sym_SLASH_SLASH] = anon_sym_SLASH_SLASH,
    [aux_sym_comment_token1] = aux_sym_comment_token1,
    [sym__NEWLINE] = sym__NEWLINE,
    [sym__WHITE_SPACE] = sym__WHITE_SPACE,
    [sym__eof] = sym__eof,
    [sym_title_h0_marker] = sym_title_h0_marker,
    [sym_title_h1_marker] = sym_title_h1_marker,
    [sym_title_h2_marker] = sym_title_h2_marker,
    [sym_title_h3_marker] = sym_title_h3_marker,
    [sym_title_h4_marker] = sym_title_h4_marker,
    [sym_title_h5_marker] = sym_title_h5_marker,
    [sym_list_marker_star] = sym_list_marker_star,
    [sym_list_marker_hyphen] = sym_list_marker_hyphen,
    [sym_list_marker_dot] = sym_list_marker_dot,
    [sym_list_marker_digit] = sym_list_marker_digit,
    [sym_list_marker_geek] = sym_list_marker_geek,
    [sym_list_marker_alpha] = sym_list_marker_alpha,
    [sym_document_attr_marker] = sym_document_attr_marker,
    [sym_element_attr_marker] = sym_element_attr_marker,
    [sym_document] = sym_document,
    [sym__section_block] = sym__section_block,
    [sym_title0] = sym_title0,
    [sym_title1] = sym_title1,
    [sym_title2] = sym_title2,
    [sym_title3] = sym_title3,
    [sym_title4] = sym_title4,
    [sym_title5] = sym_title5,
    [sym_document_attr] = sym_document_attr,
    [sym_element_attr] = sym_element_attr,
    [sym_checked_list] = sym_checked_list,
    [sym_ck_item] = sym_ck_item,
    [sym_unordered_list] = sym_unordered_list,
    [sym_ul_item] = sym_ul_item,
    [sym_unordered_list_marker] = sym_unordered_list_marker,
    [sym_ordered_list] = sym_ordered_list,
    [sym_ol_item] = sym_ol_item,
    [sym_ordered_list_marker] = sym_ordered_list_marker,
    [sym_line] = sym_line,
    [sym_comment] = sym_comment,
    [sym__block_end] = sym__block_end,
    [aux_sym_document_repeat1] = aux_sym_document_repeat1,
    [aux_sym_title0_repeat1] = aux_sym_title0_repeat1,
    [aux_sym_checked_list_repeat1] = aux_sym_checked_list_repeat1,
    [aux_sym_unordered_list_repeat1] = aux_sym_unordered_list_repeat1,
    [aux_sym_ordered_list_repeat1] = aux_sym_ordered_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
    [ts_builtin_sym_end] = {
        .visible = false,
        .named = true,
    },
    [aux_sym_document_attr_token1] = {
        .visible = false,
        .named = false,
    },
    [anon_sym_COLON] = {
        .visible = true,
        .named = false,
    },
    [aux_sym_element_attr_token1] = {
        .visible = false,
        .named = false,
    },
    [anon_sym_RBRACK] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_LBRACK] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_SPACE] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_x] = {
        .visible = true,
        .named = false,
    },
    [anon_sym_STAR] = {
        .visible = true,
        .named = false,
    },
    [aux_sym_line_token1] = {
        .visible = false,
        .named = false,
    },
    [anon_sym_SLASH_SLASH] = {
        .visible = true,
        .named = false,
    },
    [aux_sym_comment_token1] = {
        .visible = false,
        .named = false,
    },
    [sym__NEWLINE] = {
        .visible = false,
        .named = true,
    },
    [sym__WHITE_SPACE] = {
        .visible = false,
        .named = true,
    },
    [sym__eof] = {
        .visible = false,
        .named = true,
    },
    [sym_title_h0_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h1_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h2_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h3_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h4_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_title_h5_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_star] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_hyphen] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_dot] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_digit] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_geek] = {
        .visible = true,
        .named = true,
    },
    [sym_list_marker_alpha] = {
        .visible = true,
        .named = true,
    },
    [sym_document_attr_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_element_attr_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_document] = {
        .visible = true,
        .named = true,
    },
    [sym__section_block] = {
        .visible = false,
        .named = true,
    },
    [sym_title0] = {
        .visible = true,
        .named = true,
    },
    [sym_title1] = {
        .visible = true,
        .named = true,
    },
    [sym_title2] = {
        .visible = true,
        .named = true,
    },
    [sym_title3] = {
        .visible = true,
        .named = true,
    },
    [sym_title4] = {
        .visible = true,
        .named = true,
    },
    [sym_title5] = {
        .visible = true,
        .named = true,
    },
    [sym_document_attr] = {
        .visible = true,
        .named = true,
    },
    [sym_element_attr] = {
        .visible = true,
        .named = true,
    },
    [sym_checked_list] = {
        .visible = true,
        .named = true,
    },
    [sym_ck_item] = {
        .visible = true,
        .named = true,
    },
    [sym_unordered_list] = {
        .visible = true,
        .named = true,
    },
    [sym_ul_item] = {
        .visible = true,
        .named = true,
    },
    [sym_unordered_list_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_ordered_list] = {
        .visible = true,
        .named = true,
    },
    [sym_ol_item] = {
        .visible = true,
        .named = true,
    },
    [sym_ordered_list_marker] = {
        .visible = true,
        .named = true,
    },
    [sym_line] = {
        .visible = true,
        .named = true,
    },
    [sym_comment] = {
        .visible = true,
        .named = true,
    },
    [sym__block_end] = {
        .visible = false,
        .named = true,
    },
    [aux_sym_document_repeat1] = {
        .visible = false,
        .named = false,
    },
    [aux_sym_title0_repeat1] = {
        .visible = false,
        .named = false,
    },
    [aux_sym_checked_list_repeat1] = {
        .visible = false,
        .named = false,
    },
    [aux_sym_unordered_list_repeat1] = {
        .visible = false,
        .named = false,
    },
    [aux_sym_ordered_list_repeat1] = {
        .visible = false,
        .named = false,
    },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
    [0] = { 0 },
};

static const uint16_t ts_non_terminal_alias_map[] = {
    0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
    [0] = 0,
    [1] = 1,
    [2] = 2,
    [3] = 3,
    [4] = 4,
    [5] = 5,
    [6] = 6,
    [7] = 7,
    [8] = 8,
    [9] = 9,
    [10] = 10,
    [11] = 11,
    [12] = 12,
    [13] = 13,
    [14] = 14,
    [15] = 15,
    [16] = 16,
    [17] = 17,
    [18] = 18,
    [19] = 19,
    [20] = 20,
    [21] = 21,
    [22] = 22,
    [23] = 23,
    [24] = 24,
    [25] = 25,
    [26] = 26,
    [27] = 27,
    [28] = 16,
    [29] = 29,
    [30] = 30,
    [31] = 31,
    [32] = 12,
    [33] = 33,
    [34] = 34,
    [35] = 16,
    [36] = 36,
    [37] = 37,
    [38] = 38,
    [39] = 39,
    [40] = 40,
    [41] = 12,
    [42] = 42,
    [43] = 43,
    [44] = 44,
    [45] = 43,
    [46] = 43,
    [47] = 47,
    [48] = 16,
    [49] = 49,
    [50] = 50,
    [51] = 51,
    [52] = 52,
    [53] = 53,
    [54] = 54,
    [55] = 43,
    [56] = 56,
    [57] = 57,
    [58] = 58,
    [59] = 12,
    [60] = 60,
    [61] = 61,
    [62] = 62,
    [63] = 63,
    [64] = 64,
    [65] = 65,
    [66] = 66,
    [67] = 67,
    [68] = 68,
    [69] = 69,
    [70] = 70,
    [71] = 71,
    [72] = 72,
    [73] = 73,
    [74] = 74,
    [75] = 75,
    [76] = 76,
    [77] = 77,
    [78] = 78,
    [79] = 79,
    [80] = 80,
    [81] = 81,
    [82] = 82,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
    START_LEXER();
    eof = lexer->eof(lexer);
    switch(state) {
        case 0:
            if(eof)
                ADVANCE(8);
            ADVANCE_MAP(
                '\t', 36,
                '\n', 35,
                '\r', 1,
                ' ', 18,
                '*', 21,
                '/', 7,
                ':', 10,
                '[', 15,
                ']', 14,
                'x', 20,
            );
            if(('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(9);
            END_STATE();
        case 1:
            if(lookahead == '\n')
                ADVANCE(35);
            END_STATE();
        case 2:
            if(lookahead == '\n')
                ADVANCE(35);
            if(lookahead == '\r')
                ADVANCE(1);
            if(lookahead == ' ')
                ADVANCE(17);
            if(lookahead == '*')
                ADVANCE(21);
            if(lookahead == '/')
                ADVANCE(7);
            if(lookahead == 'x')
                ADVANCE(19);
            END_STATE();
        case 3:
            if(lookahead == '\n')
                ADVANCE(35);
            if(lookahead == '\r')
                ADVANCE(1);
            if(lookahead == '/')
                ADVANCE(7);
            if(lookahead == '\t' ||
               lookahead == ' ')
                ADVANCE(36);
            if(('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(9);
            END_STATE();
        case 4:
            if(lookahead == '\n')
                ADVANCE(35);
            if(lookahead == '\r')
                ADVANCE(22);
            if(lookahead == '/')
                ADVANCE(23);
            if(lookahead == '[')
                ADVANCE(16);
            if(lookahead != 0)
                ADVANCE(24);
            END_STATE();
        case 5:
            if(lookahead == '\n')
                ADVANCE(35);
            if(lookahead == '\r')
                ADVANCE(22);
            if(lookahead == '/')
                ADVANCE(23);
            if(lookahead != 0)
                ADVANCE(24);
            END_STATE();
        case 6:
            if(lookahead == '\r')
                ADVANCE(34);
            if(lookahead == '\\')
                ADVANCE(31);
            if(lookahead != 0)
                ADVANCE(33);
            END_STATE();
        case 7:
            if(lookahead == '/')
                ADVANCE(25);
            END_STATE();
        case 8:
            ACCEPT_TOKEN(ts_builtin_sym_end);
            END_STATE();
        case 9:
            ACCEPT_TOKEN(aux_sym_document_attr_token1);
            if(lookahead == '-' ||
               ('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(9);
            END_STATE();
        case 10:
            ACCEPT_TOKEN(anon_sym_COLON);
            END_STATE();
        case 11:
            ACCEPT_TOKEN(aux_sym_element_attr_token1);
            if(lookahead == '\n')
                ADVANCE(35);
            if(lookahead == '\r')
                ADVANCE(1);
            if(lookahead == '/')
                ADVANCE(12);
            if(lookahead != 0 &&
               lookahead != ']')
                ADVANCE(13);
            END_STATE();
        case 12:
            ACCEPT_TOKEN(aux_sym_element_attr_token1);
            if(lookahead == '/')
                ADVANCE(27);
            if(lookahead != 0 &&
               lookahead != '\n' &&
               lookahead != '\r' &&
               lookahead != ']')
                ADVANCE(13);
            END_STATE();
        case 13:
            ACCEPT_TOKEN(aux_sym_element_attr_token1);
            if(lookahead != 0 &&
               lookahead != '\n' &&
               lookahead != '\r' &&
               lookahead != ']')
                ADVANCE(13);
            END_STATE();
        case 14:
            ACCEPT_TOKEN(anon_sym_RBRACK);
            END_STATE();
        case 15:
            ACCEPT_TOKEN(anon_sym_LBRACK);
            END_STATE();
        case 16:
            ACCEPT_TOKEN(anon_sym_LBRACK);
            if(lookahead != 0 &&
               lookahead != '\n')
                ADVANCE(24);
            END_STATE();
        case 17:
            ACCEPT_TOKEN(anon_sym_SPACE);
            END_STATE();
        case 18:
            ACCEPT_TOKEN(anon_sym_SPACE);
            if(lookahead == '\t' ||
               lookahead == ' ')
                ADVANCE(36);
            END_STATE();
        case 19:
            ACCEPT_TOKEN(anon_sym_x);
            END_STATE();
        case 20:
            ACCEPT_TOKEN(anon_sym_x);
            if(lookahead == '-' ||
               ('0' <= lookahead && lookahead <= '9') ||
               ('A' <= lookahead && lookahead <= 'Z') ||
               lookahead == '_' ||
               ('a' <= lookahead && lookahead <= 'z'))
                ADVANCE(9);
            END_STATE();
        case 21:
            ACCEPT_TOKEN(anon_sym_STAR);
            END_STATE();
        case 22:
            ACCEPT_TOKEN(aux_sym_line_token1);
            if(lookahead == '\n')
                ADVANCE(35);
            if(lookahead != 0)
                ADVANCE(24);
            END_STATE();
        case 23:
            ACCEPT_TOKEN(aux_sym_line_token1);
            if(lookahead == '/')
                ADVANCE(28);
            if(lookahead != 0 &&
               lookahead != '\n')
                ADVANCE(24);
            END_STATE();
        case 24:
            ACCEPT_TOKEN(aux_sym_line_token1);
            if(lookahead != 0 &&
               lookahead != '\n')
                ADVANCE(24);
            END_STATE();
        case 25:
            ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
            END_STATE();
        case 26:
            ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
            if(lookahead == '\\')
                ADVANCE(6);
            if(lookahead != 0 &&
               lookahead != '\n')
                ADVANCE(33);
            END_STATE();
        case 27:
            ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
            if(lookahead != 0 &&
               lookahead != '\n' &&
               lookahead != '\r' &&
               lookahead != ']')
                ADVANCE(13);
            END_STATE();
        case 28:
            ACCEPT_TOKEN(anon_sym_SLASH_SLASH);
            if(lookahead != 0 &&
               lookahead != '\n')
                ADVANCE(24);
            END_STATE();
        case 29:
            ACCEPT_TOKEN(aux_sym_comment_token1);
            if(lookahead == '\n')
                ADVANCE(35);
            if(lookahead == '\r')
                ADVANCE(30);
            if(lookahead == '/')
                ADVANCE(32);
            if(lookahead == '\\')
                ADVANCE(6);
            if(lookahead != 0)
                ADVANCE(33);
            END_STATE();
        case 30:
            ACCEPT_TOKEN(aux_sym_comment_token1);
            if(lookahead == '\n')
                ADVANCE(35);
            if(lookahead == '\\')
                ADVANCE(6);
            if(lookahead != 0)
                ADVANCE(33);
            END_STATE();
        case 31:
            ACCEPT_TOKEN(aux_sym_comment_token1);
            if(lookahead == '\r')
                ADVANCE(34);
            if(lookahead == '\\')
                ADVANCE(31);
            if(lookahead != 0)
                ADVANCE(33);
            END_STATE();
        case 32:
            ACCEPT_TOKEN(aux_sym_comment_token1);
            if(lookahead == '/')
                ADVANCE(26);
            if(lookahead == '\\')
                ADVANCE(6);
            if(lookahead != 0 &&
               lookahead != '\n')
                ADVANCE(33);
            END_STATE();
        case 33:
            ACCEPT_TOKEN(aux_sym_comment_token1);
            if(lookahead == '\\')
                ADVANCE(6);
            if(lookahead != 0 &&
               lookahead != '\n')
                ADVANCE(33);
            END_STATE();
        case 34:
            ACCEPT_TOKEN(aux_sym_comment_token1);
            if(lookahead == '\\')
                ADVANCE(6);
            if(lookahead != 0)
                ADVANCE(33);
            END_STATE();
        case 35:
            ACCEPT_TOKEN(sym__NEWLINE);
            END_STATE();
        case 36:
            ACCEPT_TOKEN(sym__WHITE_SPACE);
            if(lookahead == '\t' ||
               lookahead == ' ')
                ADVANCE(36);
            END_STATE();
        default:
            return false;
    }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
    [0] = { .lex_state = 0, .external_lex_state = 1 },
    [1] = { .lex_state = 0, .external_lex_state = 2 },
    [2] = { .lex_state = 0, .external_lex_state = 2 },
    [3] = { .lex_state = 0, .external_lex_state = 2 },
    [4] = { .lex_state = 0, .external_lex_state = 3 },
    [5] = { .lex_state = 0, .external_lex_state = 2 },
    [6] = { .lex_state = 0, .external_lex_state = 2 },
    [7] = { .lex_state = 0, .external_lex_state = 2 },
    [8] = { .lex_state = 0, .external_lex_state = 2 },
    [9] = { .lex_state = 0, .external_lex_state = 2 },
    [10] = { .lex_state = 0, .external_lex_state = 2 },
    [11] = { .lex_state = 0, .external_lex_state = 2 },
    [12] = { .lex_state = 0, .external_lex_state = 2 },
    [13] = { .lex_state = 0, .external_lex_state = 2 },
    [14] = { .lex_state = 0, .external_lex_state = 2 },
    [15] = { .lex_state = 0, .external_lex_state = 2 },
    [16] = { .lex_state = 0, .external_lex_state = 2 },
    [17] = { .lex_state = 0, .external_lex_state = 2 },
    [18] = { .lex_state = 0, .external_lex_state = 2 },
    [19] = { .lex_state = 0, .external_lex_state = 2 },
    [20] = { .lex_state = 0, .external_lex_state = 4 },
    [21] = { .lex_state = 0, .external_lex_state = 4 },
    [22] = { .lex_state = 0, .external_lex_state = 5 },
    [23] = { .lex_state = 0, .external_lex_state = 5 },
    [24] = { .lex_state = 0, .external_lex_state = 5 },
    [25] = { .lex_state = 0, .external_lex_state = 5 },
    [26] = { .lex_state = 0, .external_lex_state = 3 },
    [27] = { .lex_state = 0, .external_lex_state = 4 },
    [28] = { .lex_state = 0, .external_lex_state = 4 },
    [29] = { .lex_state = 0, .external_lex_state = 6 },
    [30] = { .lex_state = 0, .external_lex_state = 4 },
    [31] = { .lex_state = 0, .external_lex_state = 6 },
    [32] = { .lex_state = 0, .external_lex_state = 4 },
    [33] = { .lex_state = 0, .external_lex_state = 6 },
    [34] = { .lex_state = 0, .external_lex_state = 5 },
    [35] = { .lex_state = 0, .external_lex_state = 5 },
    [36] = { .lex_state = 0, .external_lex_state = 5 },
    [37] = { .lex_state = 2 },
    [38] = { .lex_state = 4 },
    [39] = { .lex_state = 0, .external_lex_state = 5 },
    [40] = { .lex_state = 0, .external_lex_state = 5 },
    [41] = { .lex_state = 0, .external_lex_state = 5 },
    [42] = { .lex_state = 5 },
    [43] = { .lex_state = 0, .external_lex_state = 7 },
    [44] = { .lex_state = 0, .external_lex_state = 6 },
    [45] = { .lex_state = 0, .external_lex_state = 7 },
    [46] = { .lex_state = 0, .external_lex_state = 7 },
    [47] = { .lex_state = 5 },
    [48] = { .lex_state = 0, .external_lex_state = 6 },
    [49] = { .lex_state = 5 },
    [50] = { .lex_state = 0, .external_lex_state = 6 },
    [51] = { .lex_state = 5 },
    [52] = { .lex_state = 5 },
    [53] = { .lex_state = 5 },
    [54] = { .lex_state = 5 },
    [55] = { .lex_state = 0, .external_lex_state = 7 },
    [56] = { .lex_state = 5 },
    [57] = { .lex_state = 5 },
    [58] = { .lex_state = 5 },
    [59] = { .lex_state = 0, .external_lex_state = 6 },
    [60] = { .lex_state = 3 },
    [61] = { .lex_state = 3 },
    [62] = { .lex_state = 3 },
    [63] = { .lex_state = 0 },
    [64] = { .lex_state = 3 },
    [65] = { .lex_state = 0 },
    [66] = { .lex_state = 0 },
    [67] = { .lex_state = 3 },
    [68] = { .lex_state = 0 },
    [69] = { .lex_state = 3 },
    [70] = { .lex_state = 3 },
    [71] = { .lex_state = 3 },
    [72] = { .lex_state = 3 },
    [73] = { .lex_state = 3 },
    [74] = { .lex_state = 3 },
    [75] = { .lex_state = 11 },
    [76] = { .lex_state = 3 },
    [77] = { .lex_state = 0 },
    [78] = { .lex_state = 3 },
    [79] = { .lex_state = 29 },
    [80] = { .lex_state = 3 },
    [81] = { .lex_state = 0 },
    [82] = { (TSStateId)(-1) },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
    [0] = {
        [sym_comment] = STATE(0),
        [ts_builtin_sym_end] = ACTIONS(1),
        [aux_sym_document_attr_token1] = ACTIONS(1),
        [anon_sym_COLON] = ACTIONS(1),
        [anon_sym_RBRACK] = ACTIONS(1),
        [anon_sym_LBRACK] = ACTIONS(1),
        [anon_sym_SPACE] = ACTIONS(1),
        [anon_sym_x] = ACTIONS(1),
        [anon_sym_STAR] = ACTIONS(1),
        [anon_sym_SLASH_SLASH] = ACTIONS(3),
        [sym__NEWLINE] = ACTIONS(5),
        [sym__WHITE_SPACE] = ACTIONS(1),
        [sym__eof] = ACTIONS(1),
        [sym_title_h0_marker] = ACTIONS(1),
        [sym_title_h1_marker] = ACTIONS(1),
        [sym_title_h2_marker] = ACTIONS(1),
        [sym_title_h3_marker] = ACTIONS(1),
        [sym_title_h4_marker] = ACTIONS(1),
        [sym_title_h5_marker] = ACTIONS(1),
        [sym_list_marker_star] = ACTIONS(1),
        [sym_list_marker_hyphen] = ACTIONS(1),
        [sym_list_marker_dot] = ACTIONS(1),
        [sym_list_marker_digit] = ACTIONS(1),
        [sym_list_marker_geek] = ACTIONS(1),
        [sym_list_marker_alpha] = ACTIONS(1),
        [sym_document_attr_marker] = ACTIONS(1),
        [sym_element_attr_marker] = ACTIONS(1),
    },
    [1] = {
        [sym_document] = STATE(77),
        [sym__section_block] = STATE(11),
        [sym_title0] = STATE(11),
        [sym_title1] = STATE(11),
        [sym_title2] = STATE(11),
        [sym_title3] = STATE(11),
        [sym_title4] = STATE(11),
        [sym_title5] = STATE(11),
        [sym_element_attr] = STATE(4),
        [sym_checked_list] = STATE(13),
        [sym_ck_item] = STATE(34),
        [sym_unordered_list] = STATE(13),
        [sym_ul_item] = STATE(40),
        [sym_unordered_list_marker] = STATE(78),
        [sym_ordered_list] = STATE(13),
        [sym_ol_item] = STATE(27),
        [sym_ordered_list_marker] = STATE(80),
        [sym_comment] = STATE(1),
        [aux_sym_document_repeat1] = STATE(3),
        [aux_sym_checked_list_repeat1] = STATE(22),
        [aux_sym_unordered_list_repeat1] = STATE(23),
        [aux_sym_ordered_list_repeat1] = STATE(20),
        [ts_builtin_sym_end] = ACTIONS(7),
        [anon_sym_SLASH_SLASH] = ACTIONS(3),
        [sym__NEWLINE] = ACTIONS(5),
        [sym_title_h0_marker] = ACTIONS(9),
        [sym_title_h1_marker] = ACTIONS(11),
        [sym_title_h2_marker] = ACTIONS(13),
        [sym_title_h3_marker] = ACTIONS(15),
        [sym_title_h4_marker] = ACTIONS(17),
        [sym_title_h5_marker] = ACTIONS(19),
        [sym_list_marker_star] = ACTIONS(21),
        [sym_list_marker_hyphen] = ACTIONS(21),
        [sym_list_marker_dot] = ACTIONS(23),
        [sym_list_marker_digit] = ACTIONS(23),
        [sym_list_marker_geek] = ACTIONS(23),
        [sym_list_marker_alpha] = ACTIONS(23),
        [sym_element_attr_marker] = ACTIONS(25),
    },
    [2] = {
        [sym__section_block] = STATE(11),
        [sym_title0] = STATE(11),
        [sym_title1] = STATE(11),
        [sym_title2] = STATE(11),
        [sym_title3] = STATE(11),
        [sym_title4] = STATE(11),
        [sym_title5] = STATE(11),
        [sym_element_attr] = STATE(4),
        [sym_checked_list] = STATE(13),
        [sym_ck_item] = STATE(34),
        [sym_unordered_list] = STATE(13),
        [sym_ul_item] = STATE(40),
        [sym_unordered_list_marker] = STATE(78),
        [sym_ordered_list] = STATE(13),
        [sym_ol_item] = STATE(27),
        [sym_ordered_list_marker] = STATE(80),
        [sym_comment] = STATE(2),
        [aux_sym_document_repeat1] = STATE(2),
        [aux_sym_checked_list_repeat1] = STATE(22),
        [aux_sym_unordered_list_repeat1] = STATE(23),
        [aux_sym_ordered_list_repeat1] = STATE(20),
        [ts_builtin_sym_end] = ACTIONS(27),
        [anon_sym_SLASH_SLASH] = ACTIONS(3),
        [sym__NEWLINE] = ACTIONS(5),
        [sym_title_h0_marker] = ACTIONS(29),
        [sym_title_h1_marker] = ACTIONS(32),
        [sym_title_h2_marker] = ACTIONS(35),
        [sym_title_h3_marker] = ACTIONS(38),
        [sym_title_h4_marker] = ACTIONS(41),
        [sym_title_h5_marker] = ACTIONS(44),
        [sym_list_marker_star] = ACTIONS(47),
        [sym_list_marker_hyphen] = ACTIONS(47),
        [sym_list_marker_dot] = ACTIONS(50),
        [sym_list_marker_digit] = ACTIONS(50),
        [sym_list_marker_geek] = ACTIONS(50),
        [sym_list_marker_alpha] = ACTIONS(50),
        [sym_element_attr_marker] = ACTIONS(53),
    },
    [3] = {
        [sym__section_block] = STATE(11),
        [sym_title0] = STATE(11),
        [sym_title1] = STATE(11),
        [sym_title2] = STATE(11),
        [sym_title3] = STATE(11),
        [sym_title4] = STATE(11),
        [sym_title5] = STATE(11),
        [sym_element_attr] = STATE(4),
        [sym_checked_list] = STATE(13),
        [sym_ck_item] = STATE(34),
        [sym_unordered_list] = STATE(13),
        [sym_ul_item] = STATE(40),
        [sym_unordered_list_marker] = STATE(78),
        [sym_ordered_list] = STATE(13),
        [sym_ol_item] = STATE(27),
        [sym_ordered_list_marker] = STATE(80),
        [sym_comment] = STATE(3),
        [aux_sym_document_repeat1] = STATE(2),
        [aux_sym_checked_list_repeat1] = STATE(22),
        [aux_sym_unordered_list_repeat1] = STATE(23),
        [aux_sym_ordered_list_repeat1] = STATE(20),
        [ts_builtin_sym_end] = ACTIONS(56),
        [anon_sym_SLASH_SLASH] = ACTIONS(3),
        [sym__NEWLINE] = ACTIONS(5),
        [sym_title_h0_marker] = ACTIONS(9),
        [sym_title_h1_marker] = ACTIONS(11),
        [sym_title_h2_marker] = ACTIONS(13),
        [sym_title_h3_marker] = ACTIONS(15),
        [sym_title_h4_marker] = ACTIONS(17),
        [sym_title_h5_marker] = ACTIONS(19),
        [sym_list_marker_star] = ACTIONS(21),
        [sym_list_marker_hyphen] = ACTIONS(21),
        [sym_list_marker_dot] = ACTIONS(23),
        [sym_list_marker_digit] = ACTIONS(23),
        [sym_list_marker_geek] = ACTIONS(23),
        [sym_list_marker_alpha] = ACTIONS(23),
        [sym_element_attr_marker] = ACTIONS(25),
    },
};

static const uint16_t ts_small_parse_table[] = {
    [0] = 14,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(4),
    1,
    sym_comment,
    STATE(20),
    1,
    aux_sym_ordered_list_repeat1,
    STATE(22),
    1,
    aux_sym_checked_list_repeat1,
    STATE(23),
    1,
    aux_sym_unordered_list_repeat1,
    STATE(27),
    1,
    sym_ol_item,
    STATE(34),
    1,
    sym_ck_item,
    STATE(40),
    1,
    sym_ul_item,
    STATE(78),
    1,
    sym_unordered_list_marker,
    STATE(80),
    1,
    sym_ordered_list_marker,
    ACTIONS(21),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    STATE(10),
    3,
    sym_checked_list,
    sym_unordered_list,
    sym_ordered_list,
    ACTIONS(23),
    4,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    [49] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(5),
    1,
    sym_comment,
    ACTIONS(58),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [75] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(6),
    1,
    sym_comment,
    ACTIONS(60),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [101] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(7),
    1,
    sym_comment,
    ACTIONS(62),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [127] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(8),
    1,
    sym_comment,
    ACTIONS(64),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [153] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(9),
    1,
    sym_comment,
    ACTIONS(66),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [179] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(10),
    1,
    sym_comment,
    ACTIONS(68),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [205] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(11),
    1,
    sym_comment,
    ACTIONS(70),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [231] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(12),
    1,
    sym_comment,
    ACTIONS(72),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [257] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(13),
    1,
    sym_comment,
    ACTIONS(74),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [283] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(14),
    1,
    sym_comment,
    ACTIONS(76),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [309] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(15),
    1,
    sym_comment,
    ACTIONS(78),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [335] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(16),
    1,
    sym_comment,
    ACTIONS(80),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [361] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(17),
    1,
    sym_comment,
    ACTIONS(82),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [387] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(18),
    1,
    sym_comment,
    ACTIONS(84),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [413] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(19),
    1,
    sym_comment,
    ACTIONS(86),
    14,
    sym_title_h0_marker,
    sym_title_h1_marker,
    sym_title_h2_marker,
    sym_title_h3_marker,
    sym_title_h4_marker,
    sym_title_h5_marker,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym_element_attr_marker,
    ts_builtin_sym_end,
    [439] = 8,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(5),
    1,
    sym__block_end,
    STATE(20),
    1,
    sym_comment,
    STATE(21),
    1,
    aux_sym_ordered_list_repeat1,
    STATE(27),
    1,
    sym_ol_item,
    STATE(80),
    1,
    sym_ordered_list_marker,
    ACTIONS(88),
    2,
    sym__eof,
    sym__NEWLINE,
    ACTIONS(23),
    4,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    [468] = 6,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(27),
    1,
    sym_ol_item,
    STATE(80),
    1,
    sym_ordered_list_marker,
    ACTIONS(90),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(21),
    2,
    sym_comment,
    aux_sym_ordered_list_repeat1,
    ACTIONS(92),
    4,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    [492] = 8,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(18),
    1,
    sym__block_end,
    STATE(22),
    1,
    sym_comment,
    STATE(25),
    1,
    aux_sym_checked_list_repeat1,
    STATE(34),
    1,
    sym_ck_item,
    STATE(70),
    1,
    sym_unordered_list_marker,
    ACTIONS(21),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    ACTIONS(88),
    2,
    sym__eof,
    sym__NEWLINE,
    [519] = 8,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(15),
    1,
    sym__block_end,
    STATE(23),
    1,
    sym_comment,
    STATE(24),
    1,
    aux_sym_unordered_list_repeat1,
    STATE(40),
    1,
    sym_ul_item,
    STATE(60),
    1,
    sym_unordered_list_marker,
    ACTIONS(21),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    ACTIONS(88),
    2,
    sym__eof,
    sym__NEWLINE,
    [546] = 6,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(40),
    1,
    sym_ul_item,
    STATE(60),
    1,
    sym_unordered_list_marker,
    ACTIONS(95),
    2,
    sym__eof,
    sym__NEWLINE,
    ACTIONS(97),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    STATE(24),
    2,
    sym_comment,
    aux_sym_unordered_list_repeat1,
    [568] = 6,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(34),
    1,
    sym_ck_item,
    STATE(70),
    1,
    sym_unordered_list_marker,
    ACTIONS(100),
    2,
    sym__eof,
    sym__NEWLINE,
    ACTIONS(102),
    2,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    STATE(25),
    2,
    sym_comment,
    aux_sym_checked_list_repeat1,
    [590] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(26),
    1,
    sym_comment,
    ACTIONS(105),
    6,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    [608] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(27),
    1,
    sym_comment,
    ACTIONS(107),
    6,
    sym__eof,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym__NEWLINE,
    [623] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(28),
    1,
    sym_comment,
    ACTIONS(80),
    6,
    sym__eof,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym__NEWLINE,
    [638] = 7,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(109),
    1,
    sym_document_attr_marker,
    STATE(19),
    1,
    sym__block_end,
    STATE(29),
    1,
    sym_comment,
    STATE(33),
    1,
    aux_sym_title0_repeat1,
    STATE(44),
    1,
    sym_document_attr,
    ACTIONS(88),
    2,
    sym__eof,
    sym__NEWLINE,
    [661] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(30),
    1,
    sym_comment,
    ACTIONS(111),
    6,
    sym__eof,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym__NEWLINE,
    [676] = 7,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(109),
    1,
    sym_document_attr_marker,
    STATE(17),
    1,
    sym__block_end,
    STATE(29),
    1,
    aux_sym_title0_repeat1,
    STATE(31),
    1,
    sym_comment,
    STATE(44),
    1,
    sym_document_attr,
    ACTIONS(88),
    2,
    sym__eof,
    sym__NEWLINE,
    [699] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(32),
    1,
    sym_comment,
    ACTIONS(72),
    6,
    sym__eof,
    sym_list_marker_dot,
    sym_list_marker_digit,
    sym_list_marker_geek,
    sym_list_marker_alpha,
    sym__NEWLINE,
    [714] = 5,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(115),
    1,
    sym_document_attr_marker,
    STATE(44),
    1,
    sym_document_attr,
    ACTIONS(113),
    2,
    sym__eof,
    sym__NEWLINE,
    STATE(33),
    2,
    sym_comment,
    aux_sym_title0_repeat1,
    [732] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(34),
    1,
    sym_comment,
    ACTIONS(118),
    4,
    sym__eof,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym__NEWLINE,
    [745] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(35),
    1,
    sym_comment,
    ACTIONS(80),
    4,
    sym__eof,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym__NEWLINE,
    [758] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(36),
    1,
    sym_comment,
    ACTIONS(120),
    4,
    sym__eof,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym__NEWLINE,
    [771] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    STATE(37),
    1,
    sym_comment,
    ACTIONS(122),
    3,
    anon_sym_SPACE,
    anon_sym_x,
    anon_sym_STAR,
    [786] = 6,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(124),
    1,
    anon_sym_LBRACK,
    ACTIONS(126),
    1,
    aux_sym_line_token1,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    STATE(36),
    1,
    sym_line,
    STATE(38),
    1,
    sym_comment,
    [805] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(39),
    1,
    sym_comment,
    ACTIONS(130),
    4,
    sym__eof,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym__NEWLINE,
    [818] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(40),
    1,
    sym_comment,
    ACTIONS(132),
    4,
    sym__eof,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym__NEWLINE,
    [831] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(41),
    1,
    sym_comment,
    ACTIONS(72),
    4,
    sym__eof,
    sym_list_marker_star,
    sym_list_marker_hyphen,
    sym__NEWLINE,
    [844] = 5,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(134),
    1,
    aux_sym_line_token1,
    STATE(31),
    1,
    sym_line,
    STATE(42),
    1,
    sym_comment,
    [860] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(41),
    1,
    sym__block_end,
    STATE(43),
    1,
    sym_comment,
    ACTIONS(136),
    2,
    sym__eof,
    sym__NEWLINE,
    [874] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(44),
    1,
    sym_comment,
    ACTIONS(138),
    3,
    sym__eof,
    sym_document_attr_marker,
    sym__NEWLINE,
    [886] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(12),
    1,
    sym__block_end,
    STATE(45),
    1,
    sym_comment,
    ACTIONS(88),
    2,
    sym__eof,
    sym__NEWLINE,
    [900] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(46),
    1,
    sym_comment,
    STATE(59),
    1,
    sym__block_end,
    ACTIONS(140),
    2,
    sym__eof,
    sym__NEWLINE,
    [914] = 5,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(142),
    1,
    aux_sym_line_token1,
    STATE(6),
    1,
    sym_line,
    STATE(47),
    1,
    sym_comment,
    [930] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(48),
    1,
    sym_comment,
    ACTIONS(80),
    3,
    sym__eof,
    sym_document_attr_marker,
    sym__NEWLINE,
    [942] = 5,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(142),
    1,
    aux_sym_line_token1,
    STATE(14),
    1,
    sym_line,
    STATE(49),
    1,
    sym_comment,
    [958] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(50),
    1,
    sym_comment,
    ACTIONS(144),
    3,
    sym__eof,
    sym_document_attr_marker,
    sym__NEWLINE,
    [970] = 5,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(126),
    1,
    aux_sym_line_token1,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    STATE(39),
    1,
    sym_line,
    STATE(51),
    1,
    sym_comment,
    [986] = 5,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(134),
    1,
    aux_sym_line_token1,
    STATE(50),
    1,
    sym_line,
    STATE(52),
    1,
    sym_comment,
    [1002] = 5,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(142),
    1,
    aux_sym_line_token1,
    STATE(7),
    1,
    sym_line,
    STATE(53),
    1,
    sym_comment,
    [1018] = 5,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(146),
    1,
    aux_sym_line_token1,
    STATE(30),
    1,
    sym_line,
    STATE(54),
    1,
    sym_comment,
    [1034] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(32),
    1,
    sym__block_end,
    STATE(55),
    1,
    sym_comment,
    ACTIONS(148),
    2,
    sym__eof,
    sym__NEWLINE,
    [1048] = 5,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(142),
    1,
    aux_sym_line_token1,
    STATE(8),
    1,
    sym_line,
    STATE(56),
    1,
    sym_comment,
    [1064] = 5,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(142),
    1,
    aux_sym_line_token1,
    STATE(9),
    1,
    sym_line,
    STATE(57),
    1,
    sym_comment,
    [1080] = 5,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(126),
    1,
    aux_sym_line_token1,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    STATE(36),
    1,
    sym_line,
    STATE(58),
    1,
    sym_comment,
    [1096] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    STATE(59),
    1,
    sym_comment,
    ACTIONS(72),
    3,
    sym__eof,
    sym_document_attr_marker,
    sym__NEWLINE,
    [1108] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(150),
    1,
    sym__WHITE_SPACE,
    STATE(60),
    1,
    sym_comment,
    [1121] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(152),
    1,
    sym__WHITE_SPACE,
    STATE(61),
    1,
    sym_comment,
    [1134] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(154),
    1,
    sym__WHITE_SPACE,
    STATE(62),
    1,
    sym_comment,
    [1147] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(156),
    1,
    anon_sym_RBRACK,
    STATE(63),
    1,
    sym_comment,
    [1160] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(158),
    1,
    sym__WHITE_SPACE,
    STATE(64),
    1,
    sym_comment,
    [1173] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(160),
    1,
    anon_sym_RBRACK,
    STATE(65),
    1,
    sym_comment,
    [1186] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(162),
    1,
    anon_sym_COLON,
    STATE(66),
    1,
    sym_comment,
    [1199] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(164),
    1,
    sym__WHITE_SPACE,
    STATE(67),
    1,
    sym_comment,
    [1212] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(166),
    1,
    anon_sym_LBRACK,
    STATE(68),
    1,
    sym_comment,
    [1225] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(168),
    1,
    sym__WHITE_SPACE,
    STATE(69),
    1,
    sym_comment,
    [1238] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(170),
    1,
    sym__WHITE_SPACE,
    STATE(70),
    1,
    sym_comment,
    [1251] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(172),
    1,
    aux_sym_document_attr_token1,
    STATE(71),
    1,
    sym_comment,
    [1264] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(174),
    1,
    sym__WHITE_SPACE,
    STATE(72),
    1,
    sym_comment,
    [1277] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(176),
    1,
    sym__WHITE_SPACE,
    STATE(73),
    1,
    sym_comment,
    [1290] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(178),
    1,
    sym__WHITE_SPACE,
    STATE(74),
    1,
    sym_comment,
    [1303] = 4,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(180),
    1,
    aux_sym_element_attr_token1,
    STATE(75),
    1,
    sym_comment,
    [1316] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(182),
    1,
    sym__WHITE_SPACE,
    STATE(76),
    1,
    sym_comment,
    [1329] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(184),
    1,
    ts_builtin_sym_end,
    STATE(77),
    1,
    sym_comment,
    [1342] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(186),
    1,
    sym__WHITE_SPACE,
    STATE(78),
    1,
    sym_comment,
    [1355] = 4,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(128),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(188),
    1,
    aux_sym_comment_token1,
    STATE(79),
    1,
    sym_comment,
    [1368] = 4,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(5),
    1,
    sym__NEWLINE,
    ACTIONS(190),
    1,
    sym__WHITE_SPACE,
    STATE(80),
    1,
    sym_comment,
    [1381] = 3,
    ACTIONS(3),
    1,
    anon_sym_SLASH_SLASH,
    ACTIONS(192),
    1,
    sym__NEWLINE,
    STATE(81),
    1,
    sym_comment,
    [1391] = 1,
    ACTIONS(194),
    1,
    ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
    [SMALL_STATE(4)] = 0,
    [SMALL_STATE(5)] = 49,
    [SMALL_STATE(6)] = 75,
    [SMALL_STATE(7)] = 101,
    [SMALL_STATE(8)] = 127,
    [SMALL_STATE(9)] = 153,
    [SMALL_STATE(10)] = 179,
    [SMALL_STATE(11)] = 205,
    [SMALL_STATE(12)] = 231,
    [SMALL_STATE(13)] = 257,
    [SMALL_STATE(14)] = 283,
    [SMALL_STATE(15)] = 309,
    [SMALL_STATE(16)] = 335,
    [SMALL_STATE(17)] = 361,
    [SMALL_STATE(18)] = 387,
    [SMALL_STATE(19)] = 413,
    [SMALL_STATE(20)] = 439,
    [SMALL_STATE(21)] = 468,
    [SMALL_STATE(22)] = 492,
    [SMALL_STATE(23)] = 519,
    [SMALL_STATE(24)] = 546,
    [SMALL_STATE(25)] = 568,
    [SMALL_STATE(26)] = 590,
    [SMALL_STATE(27)] = 608,
    [SMALL_STATE(28)] = 623,
    [SMALL_STATE(29)] = 638,
    [SMALL_STATE(30)] = 661,
    [SMALL_STATE(31)] = 676,
    [SMALL_STATE(32)] = 699,
    [SMALL_STATE(33)] = 714,
    [SMALL_STATE(34)] = 732,
    [SMALL_STATE(35)] = 745,
    [SMALL_STATE(36)] = 758,
    [SMALL_STATE(37)] = 771,
    [SMALL_STATE(38)] = 786,
    [SMALL_STATE(39)] = 805,
    [SMALL_STATE(40)] = 818,
    [SMALL_STATE(41)] = 831,
    [SMALL_STATE(42)] = 844,
    [SMALL_STATE(43)] = 860,
    [SMALL_STATE(44)] = 874,
    [SMALL_STATE(45)] = 886,
    [SMALL_STATE(46)] = 900,
    [SMALL_STATE(47)] = 914,
    [SMALL_STATE(48)] = 930,
    [SMALL_STATE(49)] = 942,
    [SMALL_STATE(50)] = 958,
    [SMALL_STATE(51)] = 970,
    [SMALL_STATE(52)] = 986,
    [SMALL_STATE(53)] = 1002,
    [SMALL_STATE(54)] = 1018,
    [SMALL_STATE(55)] = 1034,
    [SMALL_STATE(56)] = 1048,
    [SMALL_STATE(57)] = 1064,
    [SMALL_STATE(58)] = 1080,
    [SMALL_STATE(59)] = 1096,
    [SMALL_STATE(60)] = 1108,
    [SMALL_STATE(61)] = 1121,
    [SMALL_STATE(62)] = 1134,
    [SMALL_STATE(63)] = 1147,
    [SMALL_STATE(64)] = 1160,
    [SMALL_STATE(65)] = 1173,
    [SMALL_STATE(66)] = 1186,
    [SMALL_STATE(67)] = 1199,
    [SMALL_STATE(68)] = 1212,
    [SMALL_STATE(69)] = 1225,
    [SMALL_STATE(70)] = 1238,
    [SMALL_STATE(71)] = 1251,
    [SMALL_STATE(72)] = 1264,
    [SMALL_STATE(73)] = 1277,
    [SMALL_STATE(74)] = 1290,
    [SMALL_STATE(75)] = 1303,
    [SMALL_STATE(76)] = 1316,
    [SMALL_STATE(77)] = 1329,
    [SMALL_STATE(78)] = 1342,
    [SMALL_STATE(79)] = 1355,
    [SMALL_STATE(80)] = 1368,
    [SMALL_STATE(81)] = 1381,
    [SMALL_STATE(82)] = 1391,
};

static const TSParseActionEntry ts_parse_actions[] = {
    [0] = { .entry = { .count = 0, .reusable = false } },
    [1] = { .entry = { .count = 1, .reusable = false } },
    RECOVER(),
    [3] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(79),
    [5] = { .entry = { .count = 1, .reusable = true } },
    SHIFT_EXTRA(),
    [7] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_document, 0, 0, 0),
    [9] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(76),
    [11] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(67),
    [13] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(64),
    [15] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(62),
    [17] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(61),
    [19] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(72),
    [21] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(73),
    [23] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(74),
    [25] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(75),
    [27] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    [29] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(76),
    [32] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(67),
    [35] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(64),
    [38] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(62),
    [41] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(61),
    [44] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(72),
    [47] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(73),
    [50] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(74),
    [53] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 2, 0, 0),
    SHIFT_REPEAT(75),
    [56] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_document, 1, 0, 0),
    [58] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ordered_list, 2, 0, 0),
    [60] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title4, 3, 0, 0),
    [62] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title3, 3, 0, 0),
    [64] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title2, 3, 0, 0),
    [66] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title1, 3, 0, 0),
    [68] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym__section_block, 2, 0, 0),
    [70] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_document_repeat1, 1, 0, 0),
    [72] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_line, 2, 0, 0),
    [74] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym__section_block, 1, 0, 0),
    [76] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title5, 3, 0, 0),
    [78] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_unordered_list, 2, 0, 0),
    [80] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym__block_end, 1, 0, 0),
    [82] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title0, 4, 0, 0),
    [84] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_checked_list, 2, 0, 0),
    [86] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_title0, 5, 0, 0),
    [88] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(16),
    [90] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_ordered_list_repeat1, 2, 0, 0),
    [92] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_ordered_list_repeat1, 2, 0, 0),
    SHIFT_REPEAT(74),
    [95] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_unordered_list_repeat1, 2, 0, 0),
    [97] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_unordered_list_repeat1, 2, 0, 0),
    SHIFT_REPEAT(73),
    [100] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_checked_list_repeat1, 2, 0, 0),
    [102] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_checked_list_repeat1, 2, 0, 0),
    SHIFT_REPEAT(73),
    [105] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_element_attr, 4, 0, 0),
    [107] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_ordered_list_repeat1, 1, 0, 0),
    [109] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(71),
    [111] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ol_item, 3, 0, 0),
    [113] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_title0_repeat1, 2, 0, 0),
    [115] = { .entry = { .count = 2, .reusable = true } },
    REDUCE(aux_sym_title0_repeat1, 2, 0, 0),
    SHIFT_REPEAT(71),
    [118] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_checked_list_repeat1, 1, 0, 0),
    [120] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ul_item, 3, 0, 0),
    [122] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(65),
    [124] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(37),
    [126] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(43),
    [128] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(79),
    [130] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ck_item, 7, 0, 0),
    [132] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_unordered_list_repeat1, 1, 0, 0),
    [134] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(46),
    [136] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(35),
    [138] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(aux_sym_title0_repeat1, 1, 0, 0),
    [140] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(48),
    [142] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(45),
    [144] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_document_attr, 4, 0, 0),
    [146] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(55),
    [148] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(28),
    [150] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(58),
    [152] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(47),
    [154] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(53),
    [156] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(81),
    [158] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(56),
    [160] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(69),
    [162] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(52),
    [164] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(57),
    [166] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(37),
    [168] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(51),
    [170] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(68),
    [172] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(66),
    [174] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(49),
    [176] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_unordered_list_marker, 1, 0, 0),
    [178] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_ordered_list_marker, 1, 0, 0),
    [180] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(63),
    [182] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(42),
    [184] = { .entry = { .count = 1, .reusable = true } },
    ACCEPT_INPUT(),
    [186] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(38),
    [188] = { .entry = { .count = 1, .reusable = false } },
    SHIFT(82),
    [190] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(54),
    [192] = { .entry = { .count = 1, .reusable = true } },
    SHIFT(26),
    [194] = { .entry = { .count = 1, .reusable = true } },
    REDUCE(sym_comment, 2, 0, 0),
};

enum ts_external_scanner_symbol_identifiers {
    ts_external_token__eof = 0,
    ts_external_token_title_h0_marker = 1,
    ts_external_token_title_h1_marker = 2,
    ts_external_token_title_h2_marker = 3,
    ts_external_token_title_h3_marker = 4,
    ts_external_token_title_h4_marker = 5,
    ts_external_token_title_h5_marker = 6,
    ts_external_token_list_marker_star = 7,
    ts_external_token_list_marker_hyphen = 8,
    ts_external_token_list_marker_dot = 9,
    ts_external_token_list_marker_digit = 10,
    ts_external_token_list_marker_geek = 11,
    ts_external_token_list_marker_alpha = 12,
    ts_external_token_document_attr_marker = 13,
    ts_external_token_element_attr_marker = 14,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
    [ts_external_token__eof] = sym__eof,
    [ts_external_token_title_h0_marker] = sym_title_h0_marker,
    [ts_external_token_title_h1_marker] = sym_title_h1_marker,
    [ts_external_token_title_h2_marker] = sym_title_h2_marker,
    [ts_external_token_title_h3_marker] = sym_title_h3_marker,
    [ts_external_token_title_h4_marker] = sym_title_h4_marker,
    [ts_external_token_title_h5_marker] = sym_title_h5_marker,
    [ts_external_token_list_marker_star] = sym_list_marker_star,
    [ts_external_token_list_marker_hyphen] = sym_list_marker_hyphen,
    [ts_external_token_list_marker_dot] = sym_list_marker_dot,
    [ts_external_token_list_marker_digit] = sym_list_marker_digit,
    [ts_external_token_list_marker_geek] = sym_list_marker_geek,
    [ts_external_token_list_marker_alpha] = sym_list_marker_alpha,
    [ts_external_token_document_attr_marker] = sym_document_attr_marker,
    [ts_external_token_element_attr_marker] = sym_element_attr_marker,
};

static const bool ts_external_scanner_states[8][EXTERNAL_TOKEN_COUNT] = {
    [1] = {
        [ts_external_token__eof] = true,
        [ts_external_token_title_h0_marker] = true,
        [ts_external_token_title_h1_marker] = true,
        [ts_external_token_title_h2_marker] = true,
        [ts_external_token_title_h3_marker] = true,
        [ts_external_token_title_h4_marker] = true,
        [ts_external_token_title_h5_marker] = true,
        [ts_external_token_list_marker_star] = true,
        [ts_external_token_list_marker_hyphen] = true,
        [ts_external_token_list_marker_dot] = true,
        [ts_external_token_list_marker_digit] = true,
        [ts_external_token_list_marker_geek] = true,
        [ts_external_token_list_marker_alpha] = true,
        [ts_external_token_document_attr_marker] = true,
        [ts_external_token_element_attr_marker] = true,
    },
    [2] = {
        [ts_external_token_title_h0_marker] = true,
        [ts_external_token_title_h1_marker] = true,
        [ts_external_token_title_h2_marker] = true,
        [ts_external_token_title_h3_marker] = true,
        [ts_external_token_title_h4_marker] = true,
        [ts_external_token_title_h5_marker] = true,
        [ts_external_token_list_marker_star] = true,
        [ts_external_token_list_marker_hyphen] = true,
        [ts_external_token_list_marker_dot] = true,
        [ts_external_token_list_marker_digit] = true,
        [ts_external_token_list_marker_geek] = true,
        [ts_external_token_list_marker_alpha] = true,
        [ts_external_token_element_attr_marker] = true,
    },
    [3] = {
        [ts_external_token_list_marker_star] = true,
        [ts_external_token_list_marker_hyphen] = true,
        [ts_external_token_list_marker_dot] = true,
        [ts_external_token_list_marker_digit] = true,
        [ts_external_token_list_marker_geek] = true,
        [ts_external_token_list_marker_alpha] = true,
    },
    [4] = {
        [ts_external_token__eof] = true,
        [ts_external_token_list_marker_dot] = true,
        [ts_external_token_list_marker_digit] = true,
        [ts_external_token_list_marker_geek] = true,
        [ts_external_token_list_marker_alpha] = true,
    },
    [5] = {
        [ts_external_token__eof] = true,
        [ts_external_token_list_marker_star] = true,
        [ts_external_token_list_marker_hyphen] = true,
    },
    [6] = {
        [ts_external_token__eof] = true,
        [ts_external_token_document_attr_marker] = true,
    },
    [7] = {
        [ts_external_token__eof] = true,
    },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_asciidoc_external_scanner_create(void);
void tree_sitter_asciidoc_external_scanner_destroy(void *);
bool tree_sitter_asciidoc_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_asciidoc_external_scanner_serialize(void *, char *);
void tree_sitter_asciidoc_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_asciidoc(void) {
    static const TSLanguage language = {
        .version = LANGUAGE_VERSION,
        .symbol_count = SYMBOL_COUNT,
        .alias_count = ALIAS_COUNT,
        .token_count = TOKEN_COUNT,
        .external_token_count = EXTERNAL_TOKEN_COUNT,
        .state_count = STATE_COUNT,
        .large_state_count = LARGE_STATE_COUNT,
        .production_id_count = PRODUCTION_ID_COUNT,
        .field_count = FIELD_COUNT,
        .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
        .parse_table = &ts_parse_table[0][0],
        .small_parse_table = ts_small_parse_table,
        .small_parse_table_map = ts_small_parse_table_map,
        .parse_actions = ts_parse_actions,
        .symbol_names = ts_symbol_names,
        .symbol_metadata = ts_symbol_metadata,
        .public_symbol_map = ts_symbol_map,
        .alias_map = ts_non_terminal_alias_map,
        .alias_sequences = &ts_alias_sequences[0][0],
        .lex_modes = ts_lex_modes,
        .lex_fn = ts_lex,
        .external_scanner = {
            &ts_external_scanner_states[0][0],
            ts_external_scanner_symbol_map,
            tree_sitter_asciidoc_external_scanner_create,
            tree_sitter_asciidoc_external_scanner_destroy,
            tree_sitter_asciidoc_external_scanner_scan,
            tree_sitter_asciidoc_external_scanner_serialize,
            tree_sitter_asciidoc_external_scanner_deserialize,
        },
        .primary_state_ids = ts_primary_state_ids,
    };
    return &language;
}
#ifdef __cplusplus
}
#endif
