name: Publish packages

on:
  workflow_dispatch:
  push:
    tags: ['*']

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  crates:
    name: Publish Rust Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Publish to crates
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
        run: |
          bash -c 'cd tree-sitter-asciidoc && cargo publish'
          bash -c 'cd tree-sitter-asciidoc_inline && cargo publish'
